import test from 'node:test'
import assert from 'node:assert/strict'
import { parsePageRange, mapDisplayToNative, segmentColumns, mergeRegionCandidates, buildBatchJob, batchSummary } from '../src/manuscript/batch-pipeline.js'

test('batch page ranges are deterministic and bounded by input', () => { assert.deepEqual(parsePageRange('10-19'), [10,11,12,13,14,15,16,17,18,19]); assert.deepEqual(parsePageRange('10'), [10]); assert.throws(() => parsePageRange('19-10'), /invalid_page_range/) })
test('display coordinates map independently to native axes', () => { assert.deepEqual(mapDisplayToNative({ x: 120, y: 240, width: 600, height: 800 }, { width: 1200, height: 2400 }, { width: 5900, height: 10400 }), { x: 590, y: 1040, width: 2950, height: 3467, scaleX: 5900 / 1200, scaleY: 10400 / 2400 }) })
test('segmentation stays inside the displayed image and separates columns', () => { const regions = segmentColumns({ width: 2400, height: 4231, columns: 2 }); assert.equal(regions.length, 4); assert.ok(regions.every((r) => r.x >= 0 && r.y >= 0 && r.x + r.width <= 2400 && r.y + r.height <= 4231)); assert.deepEqual(regions.map((r) => r.column), ['left','left','right','right']) })
test('overlapping equal lines are deduplicated and disagreements preserved', () => { const a = { regionId: 'a', column: 'left', candidate: { lines: [{ sequence: 1, diplomaticLatin: 'abc', confidence: .7 }] } }; const b = { regionId: 'b', column: 'left', candidate: { lines: [{ sequence: 1, diplomaticLatin: 'abc', confidence: .6 }, { sequence: 2, diplomaticLatin: 'xyz', confidence: .4 }] } }; const merged = mergeRegionCandidates([a,b]); assert.equal(merged.lines.length, 2); assert.equal(merged.disagreements.length, 0) })
test('job summary exposes candidate-only state', () => { const job = buildBatchJob({ sourceId: 's', pages: [10,11], provider: 'openrouter', model: 'm', jobId: 'test-job' }); assert.equal(job.canonical, false); assert.equal(job.candidateOnly, true); assert.equal(batchSummary(job).completed, 0) })
