import test from 'node:test'
import assert from 'node:assert/strict'
import { compactRegionPrompt, compactRegionSchema, extractAssistant, extractCompleteCompactLines, parseSalvage, normalizeSalvage, classifyFailure } from '../src/manuscript/batch-recovery.js'

test('salvage removes fences and surrounding prose', () => { const r = parseSalvage('Here is JSON:\n```json\n{"lines":[{"text":"arma"}]}\n```'); assert.equal(r.parsed.lines[0].text, 'arma'); assert.deepEqual(r.repairs, ['extracted_complete_json_object']) })
test('truncated JSON preserves complete objects without invention', () => { const r = parseSalvage('{"lines":[{"text":"arma"}]'); assert.equal(r.parsed.lines[0].text, 'arma'); assert.equal(r.truncated, true) })
test('structural aliases normalize without changing Latin', () => { const r = normalizeSalvage({ lines: [{ text: 'arma', confidence: '0.5' }] }, { regionId: 'r' }); assert.equal(r.candidate.lines[0].diplomaticLatin, 'arma'); assert.equal(r.candidate.lines[0].confidence, .5); assert.equal(r.candidate.applicationPolicy.canonical, false) })
test('English explanatory content is rejected', () => { const r = normalizeSalvage({ lines: [{ text: 'The image shows text' }] }, { regionId: 'r' }); assert.equal(r.candidate, null); assert.equal(r.findings[0].type, 'english_in_latin_field') })
test('failure classes are grouped deterministically', () => { assert.equal(classifyFailure({ classification: 'rate_limited' }), 'rate_limited'); assert.equal(classifyFailure({ message: 'This operation was aborted' }), 'transport_failure'); assert.equal(classifyFailure({ classification: 'malformed_json' }), 'malformed_json') })
test('compact schema and prompt exclude application metadata', () => { assert.deepEqual(compactRegionSchema.required, ['lines']); assert.match(compactRegionPrompt, /Return JSON only/); assert.doesNotMatch(compactRegionPrompt, /canonical|reviewRequired|sourceId|translation/i) })
test('complete compact line objects are salvaged from a truncated array', () => { const r = parseSalvage('{"lines":[{"n":1,"t":"arma","c":0.8,"u":false,"i":false,"p":false},{"n":2,"t":"uir","c":0.6,"u":true,"i":false,"p":false},{"n":3,"t":"incom'); assert.equal(r.truncated, true); assert.equal(r.partialResponse, true); assert.equal(r.parsed.lines.length, 2); assert.equal(r.parsed.lines[1].t, 'uir') })
test('incomplete final compact object is rejected', () => { const r = parseSalvage('{"lines":[{"n":1,"t":"arma","c":0.8,"u":false,"i":false,"p":false},{"n":2,"t":"incom'); assert.equal(r.parsed.lines.length, 1); assert.equal(r.parsed.lines[0].t, 'arma') })
test('compact fields normalize to application-owned candidate metadata', () => { const r = normalizeSalvage({ lines: [{ n: 1, t: 'arma', c: 0.8, u: true, i: false, p: true }] }, { regionId: 'compact-r' }); assert.equal(r.candidate.lines[0].diplomaticLatin, 'arma'); assert.equal(r.candidate.lines[0].partialAtStart, true); assert.equal(r.candidate.applicationPolicy.candidateOnly, true); assert.equal(r.candidate.applicationPolicy.reviewRequired, true) })
test('compact extraction never accepts English as Latin', () => { const r = normalizeSalvage({ lines: [{ n: 1, t: 'The image shows text', c: 0.8, u: false, i: false, p: false }] }, { regionId: 'english-r' }); assert.equal(r.candidate, null); assert.ok(r.findings.some((f) => f.type === 'english_in_latin_field')) })
test('Gemini envelope assistant content is extracted for salvage', () => { const r = extractAssistant(JSON.stringify({ candidates: [{ content: { parts: [{ text: '{"lines":[]}' }] } }] })); assert.equal(r.content, '{"lines":[]}') })
