import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import { contextualChunks, productionTranslationPrompt, missingTranslationSourceLines, mergeRecoveredTranslationRecords, coverage, translationPolicy, attachTerminalDisposition, segmentGate } from '../src/manuscript/translation-pipeline.js'

const lines = Array.from({ length: 12 }, (_, index) => ({ sourceLineId: `line-${index + 1}`, diplomaticLatin: `latin ${index + 1}`, sourceUncertain: false, sourceWarnings: [], regionIds: ['r'], page: 30, column: 'left', sequence: index + 1 }))
test('production translation chunks are bounded and ordered', () => { const result = contextualChunks(lines, 5, 2); assert.deepEqual(result.map((part) => part.targets.length), [5, 5, 2]); assert.deepEqual(result.flatMap((part) => part.targets.map((line) => line.sourceLineId)), lines.map((line) => line.sourceLineId)) })
test('context lines are explicitly excluded from provider output targets', () => { const prompt = productionTranslationPrompt(lines.slice(2, 4), lines.slice(0, 2)); assert.match(prompt, /MUST NOT be emitted/); assert.match(prompt, /Targets/); const context = prompt.match(/Context \(not output targets\): (.*)\. Targets:/)?.[1]; assert.ok(context); assert.doesNotMatch(context, /"k":/); assert.match(prompt, /"k":"L1"/); assert.match(prompt, /"k":"L2"/) })
test('completed lines are skipped on resume', () => { const records = lines.map((line, index) => ({ ...line, literalEnglish: index ? '' : 'Latin one', readableEnglish: index ? '' : 'Latin one.' })); assert.equal(missingTranslationSourceLines(records, lines).length, 11); assert.equal(missingTranslationSourceLines(records, lines)[0].sourceLineId, 'line-2') })
test('recovery preserves source identity and adds provider provenance', () => { const records = [{ ...lines[0], literalEnglish: '', readableEnglish: '', warnings: ['translation_missing'], attemptHistory: [] }]; const recovered = [{ ...records[0], expandedLatin: 'latinum', literalEnglish: 'the Latin', readableEnglish: 'The Latin.', warnings: [] }]; const merged = mergeRecoveredTranslationRecords(records, recovered, { provider: 'mistral', model: 'mistral-small-2603', rawResponseHash: 'a', promptHash: 'b' }); assert.equal(merged[0].sourceLineId, lines[0].sourceLineId); assert.equal(merged[0].translationProvider, 'mistral'); assert.equal(merged[0].attemptHistory.length, 1) })
test('untranslated records remain represented in coverage', () => { const result = coverage([{ expandedLatin: '', literalEnglish: '', readableEnglish: '', warnings: ['translation_missing'] }]); assert.equal(result.sourceLatinLines, 1); assert.equal(result.untranslatedLines, 1); assert.equal(result.translationCoveragePercentage, 0) })
test('translation and disposition coverage are independent', () => { const result = coverage([{ terminalDisposition: 'translated', expandedLatin: 'a', literalEnglish: 'a', readableEnglish: 'A.' }, { terminalDisposition: 'source_ocr_corrupt', intentionallyUntranslated: true, expandedLatin: '', literalEnglish: '', readableEnglish: '' }]); assert.equal(result.translationCoveragePercentage, 50); assert.equal(result.expansionCoveragePercentage, 50); assert.equal(result.dispositionCoveragePercentage, 100); assert.equal(result.intentionallyUntranslatedLines, 1) })
test('corrupt OCR receives a stable terminal disposition without invented text', () => { const record = attachTerminalDisposition({ diplomaticLatin: 'x 7 7 7 7 7 7 7 7 7 7', sourceWarnings: [], warnings: [], literalEnglish: '', readableEnglish: '' }, { rejectionReason: 'OCR corruption too severe' }); assert.equal(record.terminalDisposition, 'source_ocr_corrupt'); assert.equal(record.intentionallyUntranslated, true); assert.equal(record.literalEnglish, '') })
test('80 percent translation and complete disposition pass the segment gate', () => { const records = Array.from({ length: 10 }, (_, index) => index < 8 ? { sourceLineId: `l${index}`, diplomaticLatin: 'latin', terminalDisposition: 'translated', literalEnglish: 'English', readableEnglish: 'Readable', expandedLatin: 'latin' } : { sourceLineId: `l${index}`, diplomaticLatin: 'corrupt', terminalDisposition: 'source_ocr_corrupt', intentionallyUntranslated: true, literalEnglish: '', readableEnglish: '', expandedLatin: '' }); const gate = segmentGate(records); assert.equal(gate.operationallyComplete, true); assert.equal(gate.coverage.translationCoveragePercentage, 80); assert.equal(gate.coverage.dispositionCoveragePercentage, 100) })
test('75 percent with complete terminal reasons becomes completed_partial after recovery', () => { const records = Array.from({ length: 4 }, (_, index) => index < 3 ? { sourceLineId: `p${index}`, diplomaticLatin: 'latin', terminalDisposition: 'translated', literalEnglish: 'English', readableEnglish: 'Readable', expandedLatin: 'latin' } : { sourceLineId: `p${index}`, diplomaticLatin: 'corrupt', terminalDisposition: 'source_ocr_corrupt', dispositionReason: 'source-quality rejection', intentionallyUntranslated: true, literalEnglish: '', readableEnglish: '', expandedLatin: '' }); const gate = segmentGate(records, { recoveryAttempted: true }); assert.equal(gate.state, 'completed_partial'); assert.equal(gate.operationallyComplete, true); assert.equal(gate.coverage.translationCoveragePercentage, 75) })
test('partial coverage requires a recovery pass and honest terminal reasons', () => { const records = Array.from({ length: 4 }, (_, index) => index < 3 ? { sourceLineId: `q${index}`, diplomaticLatin: 'latin', terminalDisposition: 'translated', literalEnglish: 'English', readableEnglish: 'Readable', expandedLatin: 'latin' } : { sourceLineId: `q${index}`, diplomaticLatin: 'corrupt', terminalDisposition: 'source_ocr_corrupt', intentionallyUntranslated: true, literalEnglish: '', readableEnglish: '', expandedLatin: '' }); assert.equal(segmentGate(records).state, 'running'); assert.notEqual(segmentGate(records, { recoveryAttempted: true }).state, 'completed_partial') })
test('65 to 75 percent becomes a terminal exception after span recovery', () => { const records = Array.from({ length: 10 }, (_, index) => index < 7 ? { sourceLineId: `e${index}`, diplomaticLatin: 'latin', terminalDisposition: 'translated', literalEnglish: 'English', readableEnglish: 'Readable', expandedLatin: 'latin' } : { sourceLineId: `e${index}`, diplomaticLatin: 'corrupt', terminalDisposition: 'source_ocr_corrupt', dispositionReason: 'source-quality rejection', intentionallyUntranslated: true, literalEnglish: '', readableEnglish: '', expandedLatin: '' }); assert.equal(segmentGate(records, { recoveryAttempted: true }).state, 'exception') })
test('an undisposed source line blocks a segment', () => { const gate = segmentGate([{ sourceLineId: 'l1', diplomaticLatin: 'latin', terminalDisposition: null, literalEnglish: '', readableEnglish: '' }]); assert.equal(gate.operationallyComplete, false); assert.ok(gate.blockers.includes('disposition_coverage_below_100')) })
test('completed and intentionally untranslated lines are skipped on resume', () => { const source = lines.slice(0, 2); const records = [{ ...source[0], terminalDisposition: 'translated', literalEnglish: 'English', readableEnglish: 'Readable' }, { ...source[1], terminalDisposition: 'source_ocr_corrupt', intentionallyUntranslated: true, literalEnglish: '', readableEnglish: '' }]; assert.equal(missingTranslationSourceLines(records, source).length, 0) })
test('production viewer has coverage labels, dispositions, navigation, and permanent warning', () => { const source = fs.readFileSync('src/editorial/translation-pilot-viewer.js', 'utf8'); assert.match(source, /Page \$\{previous\.page\}/); assert.match(source, /NOT A SCHOLARLY EDITION/); assert.match(source, /\[untranslated\]/); assert.match(source, /dispositionCoveragePercentage/); assert.match(source, /OCR corrupt/) })
test('production runner uses a configured text provider with one bounded retry', () => { const source = fs.readFileSync('scripts/translate-production.mjs', 'utf8'); assert.match(source, /readTextProviderConfig/); assert.match(source, /providerMode = 'text_provider'/); assert.match(source, /const retryDelays = \[5000\]/); assert.doesNotMatch(source, /providerConfig: secondary/) })
test('production runner accepts terminal partial and exception segments after one span pass', () => { const source = fs.readFileSync('scripts/translate-production.mjs', 'utf8'); assert.match(source, /acceptedSegmentStates = new Set\(\['completed', 'completed_partial', 'exception'\]\)/); assert.match(source, /runSpanRecoveryOnce/); assert.match(source, /if \(segment\.spanRecovery\) return/); assert.match(source, /aggregate\.dispositionCoveragePercentage < 100/); assert.doesNotMatch(source, /aggregate\.translationCoveragePercentage < 80/) })
test('viewer reports honest partial-machine status', () => { const source = fs.readFileSync('src/editorial/translation-pilot-viewer.js', 'utf8'); assert.match(source, /Completed — Partial Machine Translation/); assert.match(source, /untranslated/); assert.match(source, /human review required/) })
test('production policy remains candidate-only', () => { assert.equal(translationPolicy.canonical, false); assert.equal(translationPolicy.candidateOnly, true); assert.equal(translationPolicy.reviewRequired, true) })
