import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import { classifyUntranslatedLine, buildTranslationSpans, validateSpanTranslation, applySpanCoverage } from '../src/manuscript/translation-spans.js'
import { coverage, translationPolicy } from '../src/manuscript/translation-pipeline.js'

const line = (id, page, column, sequence, diplomaticLatin) => ({ sourceLineId: id, page, column, sequence, regionIds: [`r-${page}-${column}`], diplomaticLatin, sourceWarnings: [], warnings: [], terminalDisposition: 'source_ocr_corrupt', literalEnglish: '', readableEnglish: '' })

test('sentence fragments are not automatically classified as corrupt', () => { const item = classifyUntranslatedLine(line('l1', 50, 'left', 1, 'et dixit ad eos quod'), { before: [], after: [] }); assert.equal(item.revisedClassification, 'context_dependent_fragment') })
test('pathological repeated OCR remains genuinely corrupt', () => { const item = classifyUntranslatedLine(line('l1', 50, 'left', 1, 'sum 7 7 7 7 7 7 7 7 7 7 7'), { before: [], after: [] }); assert.equal(item.revisedClassification, 'genuinely_corrupt') })
test('spans preserve source order and never cross columns or pages', () => { const lines = [line('a', 50, 'left', 1, 'et dixit ad'), line('b', 50, 'left', 2, 'eos qui fuerant'), line('c', 50, 'right', 3, 'in domo sua'), line('d', 51, 'right', 4, 'cum fratribus')]; const classes = lines.map((item) => ({ sourceLineId: item.sourceLineId, revisedClassification: 'context_dependent_fragment' })); const spans = buildTranslationSpans(lines, classes); assert.deepEqual(spans[0].sourceLineIds, ['a', 'b']); assert.ok(spans.every((span) => new Set(span.sourceLineIds.map((id) => lines.find((item) => item.sourceLineId === id).column)).size === 1)); assert.ok(spans.every((span) => new Set(span.sourceLineIds.map((id) => lines.find((item) => item.sourceLineId === id).page)).size === 1)) })
test('validated span coverage links every contributing source line without per-line English', () => { const lines = [line('a', 50, 'left', 1, 'et dixit ad'), line('b', 50, 'left', 2, 'eos qui fuerant')]; const span = buildTranslationSpans(lines, lines.map((item) => ({ sourceLineId: item.sourceLineId, revisedClassification: 'context_dependent_fragment' })))[0]; const validation = validateSpanTranslation({ spanId: span.spanId, expandedLatin: 'et dixit ad eos qui fuerant', literalEnglish: 'and he said to those who had been', readableEnglish: 'He spoke to those who had been there.', sourceUsable: true, uncertain: true, warnings: [] }, span); assert.equal(validation.valid, true); const covered = applySpanCoverage(lines, validation.candidate); assert.ok(covered.every((item) => item.coveredBySpanId === span.spanId)); assert.ok(covered.every((item) => item.independentLineTranslation === null)); assert.equal(coverage(covered).translationCoveragePercentage, 100) })
test('duplicate and nontext dispositions remain terminal but untranslated', () => { const records = [{ ...line('a', 50, 'left', 1, 'same'), terminalDisposition: 'source_duplicate' }, { ...line('b', 50, 'left', 2, '7.'), terminalDisposition: 'source_empty' }]; const metrics = coverage(records); assert.equal(metrics.translationCoveragePercentage, 0); assert.equal(metrics.dispositionCoveragePercentage, 100) })
test('unsupported reconstruction is rejected', () => { const lines = [line('a', 50, 'left', 1, 'et dixit ad'), line('b', 50, 'left', 2, 'eos qui fuerant')]; const span = buildTranslationSpans(lines, lines.map((item) => ({ sourceLineId: item.sourceLineId, revisedClassification: 'context_dependent_fragment' })))[0]; const validation = validateSpanTranslation({ spanId: span.spanId, expandedLatin: 'et dixit', literalEnglish: 'According to the Bible, Moses said this passage', readableEnglish: 'Scripture says that Moses spoke.', sourceUsable: true, uncertain: false, warnings: [] }, span); assert.equal(validation.valid, false); assert.ok(validation.findings.some((item) => item.issue === 'unsupported_reconstruction')) })
test('span recovery skips existing valid candidates and preserves raw responses by construction', () => { const source = fs.readFileSync('scripts/recover-translation-spans.mjs', 'utf8'); assert.match(source, /span-candidate\.json/); assert.match(source, /raw-response\.txt/); assert.match(source, /validation\?\.valid/); assert.match(source, /fs\.writeFileSync/) })
test('span recovery reuses one parameterized implementation with one transient retry', () => { const source = fs.readFileSync('scripts/recover-translation-spans.mjs', 'utf8'); assert.match(source, /args\.segment \|\| args\.pages/); assert.match(source, /production\.segments\.find\(\(item\) => item\.label === segmentLabel\)/); assert.match(source, /const retryDelays = \[5000\]/); assert.doesNotMatch(source, /item\.label === '50-59'/) })
test('viewer supports span highlighting and covered-line labels', () => { const source = fs.readFileSync('src/editorial/translation-pilot-viewer.js', 'utf8'); assert.match(source, /coveredBySpanId|covered_by_span/) })
test('span output remains candidate-only', () => { assert.equal(translationPolicy.canonical, false); assert.equal(translationPolicy.reviewRequired, true) })
