import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { invokeVisionModel, invokeVisionModelSafe, invokeLiveVisionProbe, probeVisionProvider, publicConfig } from '../src/manuscript/vision-provider-runtime.js'
import { sha256 } from '../src/manuscript/source-ingestion.js'

const imagePath = path.join(process.cwd(), 'public/folios/real/002r.jpg')
const model = 'nvidia/nemotron-nano-12b-v2-vl:free'
const candidate = { schemaVersion: '1.0', project: 'Project GIGAS', status: 'unverified_ai_candidate', canonical: false, blocked: false, lines: [], reviewRequired: true }
const oldEnv = {}
const setEnv = (values) => { for (const [key, value] of Object.entries(values)) { if (!(key in oldEnv)) oldEnv[key] = process.env[key]; value === undefined ? delete process.env[key] : process.env[key] = value } }
const restoreEnv = () => { for (const [key, value] of Object.entries(oldEnv)) value === undefined ? delete process.env[key] : process.env[key] = value }
const openRouterMetadata = (extra = {}) => ({ id: model, architecture: { input_modalities: ['text', 'image'], modality: 'text+image' }, ...extra })
const mockOpenRouter = ({ metadata = openRouterMetadata(), metadataStatus = 200, metadataBody, responseBody = { choices: [{ message: { content: JSON.stringify(candidate) } }] }, responseStatus = 200 } = {}) => { const original = globalThis.fetch; const requests = []; globalThis.fetch = async (url, init = {}) => { requests.push({ url, init, payload: init.body ? JSON.parse(init.body) : null }); if (url.endsWith('/models')) return new Response(metadataBody ?? JSON.stringify({ data: metadata ? [metadata] : [] }), { status: metadataStatus }); return new Response(JSON.stringify(responseBody), { status: responseStatus, headers: { 'x-request-id': 'mock-request' } }) }; return { requests, restore: () => { globalThis.fetch = original } } }

test('unconfigured provider remains blocked without throwing', async () => { setEnv({ GIGAS_VISION_PROVIDER: undefined, GIGAS_VISION_MODEL: undefined, GIGAS_VISION_API_KEY: undefined }); const result = await invokeVisionModelSafe({ imagePath, prompt: 'test', requestId: 'blocked-test' }); assert.equal(result.status, 'blocked'); assert.equal(result.failureClassification, 'provider_error'); restoreEnv() })

test('OpenRouter exact configured free model with image input is usable', async () => { setEnv({ GIGAS_VISION_PROVIDER: 'openrouter', GIGAS_VISION_MODEL: model, GIGAS_VISION_API_KEY: 'secret', GIGAS_VISION_CAPABILITY_REFRESH: '1' }); const mock = mockOpenRouter({ metadata: openRouterMetadata({ supported_parameters: ['response_format'] }) }); const result = await probeVisionProvider(); mock.restore(); assert.equal(result.model, model); assert.equal(result.imageInput, true); assert.equal(result.structuredOutput, 'json_object'); assert.equal(result.usable, true); assert.equal(result.metadataStatus, 'verified'); restoreEnv() })

test('image capability is independent from strict structured output', async () => { setEnv({ GIGAS_VISION_PROVIDER: 'openrouter', GIGAS_VISION_MODEL: model, GIGAS_VISION_API_KEY: 'secret', GIGAS_VISION_CAPABILITY_REFRESH: '1' }); const mock = mockOpenRouter({ metadata: openRouterMetadata() }); const result = await probeVisionProvider(); mock.restore(); assert.equal(result.imageInput, true); assert.equal(result.structuredOutput, null); assert.equal(result.metadataStatus, 'partial'); assert.equal(result.usable, true); restoreEnv() })

test('basic json_object capability is selected when advertised', async () => { setEnv({ GIGAS_VISION_PROVIDER: 'openrouter', GIGAS_VISION_MODEL: model, GIGAS_VISION_API_KEY: 'secret', GIGAS_VISION_CAPABILITY_REFRESH: '1' }); const mock = mockOpenRouter({ metadata: openRouterMetadata({ supported_parameters: ['json_object'] }) }); const result = await probeVisionProvider(); mock.restore(); assert.equal(result.imageInput, true); assert.equal(result.structuredOutput, 'json_object'); assert.equal(result.usable, true); restoreEnv() })

test('missing supported_parameters does not reject image input', async () => { setEnv({ GIGAS_VISION_PROVIDER: 'openrouter', GIGAS_VISION_MODEL: model, GIGAS_VISION_API_KEY: 'secret', GIGAS_VISION_CAPABILITY_REFRESH: '1' }); const mock = mockOpenRouter({ metadata: openRouterMetadata({ supported_parameters: undefined }) }); const result = await probeVisionProvider(); mock.restore(); assert.equal(result.imageInput, true); assert.equal(result.usable, true); assert.equal(result.blocker, null); restoreEnv() })

test('metadata endpoint failure is explicit and preserves status/body', async () => { setEnv({ GIGAS_VISION_PROVIDER: 'openrouter', GIGAS_VISION_MODEL: model, GIGAS_VISION_API_KEY: 'secret', GIGAS_VISION_CAPABILITY_REFRESH: '1' }); const mock = mockOpenRouter({ metadataStatus: 503, metadataBody: '{"error":"temporarily unavailable"}' }); const result = await probeVisionProvider(); mock.restore(); assert.equal(result.imageInput, null); assert.equal(result.metadataStatus, 'unavailable'); assert.equal(result.blocker, 'metadata_lookup_failed'); assert.equal(result.metadataLookup.status, 503); assert.match(result.metadataLookup.body, /temporarily unavailable/); restoreEnv() })

test('refresh bypasses a stale cached negative result', async () => { setEnv({ GIGAS_VISION_PROVIDER: 'openrouter', GIGAS_VISION_MODEL: model, GIGAS_VISION_API_KEY: 'secret', GIGAS_VISION_CAPABILITY_REFRESH: '1' }); let mock = mockOpenRouter({ metadata: openRouterMetadata({ architecture: { input_modalities: ['text'] } }) }); const negative = await probeVisionProvider(); mock.restore(); assert.equal(negative.imageInput, false); setEnv({ GIGAS_VISION_CAPABILITY_REFRESH: '1' }); mock = mockOpenRouter({ metadata: openRouterMetadata() }); const positive = await probeVisionProvider(); mock.restore(); assert.equal(positive.imageInput, true); restoreEnv() })

test('text-only metadata is correctly rejected', async () => { setEnv({ GIGAS_VISION_PROVIDER: 'openrouter', GIGAS_VISION_MODEL: model, GIGAS_VISION_API_KEY: 'secret', GIGAS_VISION_CAPABILITY_REFRESH: '1' }); const mock = mockOpenRouter({ metadata: { id: model, architecture: { input_modalities: ['text'], modality: 'text' }, supported_parameters: ['json_object'] } }); const result = await probeVisionProvider(); mock.restore(); assert.equal(result.imageInput, false); assert.equal(result.usable, false); assert.equal(result.blocker, 'Selected routed model does not support manuscript image input.'); restoreEnv() })

test('OpenRouter request uses actual image bytes and prompt-only fallback', async () => { setEnv({ GIGAS_VISION_PROVIDER: 'openrouter', GIGAS_VISION_MODEL: model, GIGAS_VISION_API_KEY: 'secret', GIGAS_VISION_CAPABILITY_REFRESH: '1' }); const mock = mockOpenRouter({ metadata: openRouterMetadata() }); const result = await invokeVisionModel({ imagePath, prompt: 'transcribe', schema: { required: ['schemaVersion'] }, requestId: 'openrouter-image-test', expectedImageHash: sha256(fs.readFileSync(imagePath)) }); const modelRequest = mock.requests.find((request) => !request.url.endsWith('/models')); mock.restore(); assert.equal(result.status, 'completed'); assert.match(modelRequest.payload.messages[0].content[1].image_url.url, /^data:image\/jpeg;base64,/); assert.equal(modelRequest.payload.response_format, undefined); assert.equal(JSON.stringify(result).includes('secret'), false); restoreEnv() })

test('live probe sends the minimal prompt-only request with exact free model', async () => { setEnv({ GIGAS_VISION_PROVIDER: 'openrouter', GIGAS_VISION_MODEL: model, GIGAS_VISION_API_KEY: 'secret', GIGAS_VISION_CAPABILITY_REFRESH: '1' }); const mock = mockOpenRouter({ metadata: openRouterMetadata(), responseBody: { id: 'live-ok', model, choices: [{ message: { content: '{"ok":true}' } }] } }); const result = await invokeLiveVisionProbe({ imagePath, expectedImageHash: sha256(fs.readFileSync(imagePath)) }); const request = mock.requests.find((item) => !item.url.endsWith('/models')); mock.restore(); assert.equal(result.status, 'completed'); assert.equal(request.payload.model, model); assert.deepEqual(Object.keys(request.payload).sort(), ['max_tokens', 'messages', 'model', 'temperature']); assert.equal(request.payload.max_tokens, 32); assert.equal(request.payload.temperature, 0); assert.equal(request.payload.messages[0].content[1].image_url.url.startsWith('data:image/jpeg;base64,'), true); restoreEnv() })

test('live probe preserves invalid-model 400 diagnostics', async () => { setEnv({ GIGAS_VISION_PROVIDER: 'openrouter', GIGAS_VISION_MODEL: model, GIGAS_VISION_API_KEY: 'secret', GIGAS_VISION_CAPABILITY_REFRESH: '1' }); const mock = mockOpenRouter({ metadata: openRouterMetadata(), responseStatus: 400, responseBody: { error: { code: 'model_not_found', message: 'The model is unavailable.' } } }); const result = await invokeLiveVisionProbe({ imagePath }); mock.restore(); assert.equal(result.failureClassification, 'invalid_model'); assert.equal(result.httpStatus, 400); assert.equal(result.providerErrorCode, 'model_not_found'); assert.equal(result.providerErrorMessage, 'The model is unavailable.'); assert.match(result.rawResponse, /model is unavailable/); restoreEnv() })

test('live probe distinguishes unsupported parameter and malformed image 400s', async () => { setEnv({ GIGAS_VISION_PROVIDER: 'openrouter', GIGAS_VISION_MODEL: model, GIGAS_VISION_API_KEY: 'secret', GIGAS_VISION_CAPABILITY_REFRESH: '1' }); let mock = mockOpenRouter({ metadata: openRouterMetadata(), responseStatus: 400, responseBody: { error: { code: 'unsupported_parameter', message: 'response_format is not supported.' } } }); let result = await invokeLiveVisionProbe({ imagePath }); mock.restore(); assert.equal(result.failureClassification, 'unsupported_parameter'); assert.equal(result.providerErrorMessage, 'response_format is not supported.'); mock = mockOpenRouter({ metadata: openRouterMetadata(), responseStatus: 400, responseBody: { error: { code: 'invalid_image', message: 'image MIME is invalid.' } } }); result = await invokeLiveVisionProbe({ imagePath }); mock.restore(); assert.equal(result.failureClassification, 'image_rejected'); assert.equal(result.providerErrorCode, 'invalid_image'); restoreEnv() })

test('HTTP 200 embedded 504 is upstream_timeout and preserves full response', async () => { setEnv({ GIGAS_VISION_PROVIDER: 'openrouter', GIGAS_VISION_MODEL: model, GIGAS_VISION_API_KEY: 'secret', GIGAS_VISION_MAX_RETRIES: '0', GIGAS_VISION_CAPABILITY_REFRESH: '1' }); const mock = mockOpenRouter({ metadata: openRouterMetadata(), responseBody: { error: { code: 504, message: 'Upstream idle timeout exceeded' } } }); const result = await invokeVisionModel({ imagePath, requestId: 'embedded-timeout' }); mock.restore(); assert.equal(result.failureClassification, 'upstream_timeout'); assert.equal(result.httpStatus, 200); assert.equal(result.providerErrorCode, 504); assert.equal(result.providerErrorMessage, 'Upstream idle timeout exceeded'); assert.match(result.rawResponse, /Upstream idle timeout exceeded/); assert.ok(result.responseHeaders['x-request-id'] || result.responseHeaders); restoreEnv() })

test('HTTP 504 is retryable and stops at configured retry limit', async () => { setEnv({ GIGAS_VISION_PROVIDER: 'openrouter', GIGAS_VISION_MODEL: model, GIGAS_VISION_API_KEY: 'secret', GIGAS_VISION_MAX_RETRIES: '2', GIGAS_VISION_CAPABILITY_REFRESH: '1' }); const original = globalThis.fetch; let calls = 0; globalThis.fetch = async (url) => { if (url.endsWith('/models')) return new Response(JSON.stringify({ data: [openRouterMetadata()] }), { status: 200 }); calls++; return new Response(JSON.stringify({ error: { code: 504, message: 'gateway timeout' } }), { status: 504, headers: { 'x-generation-id': `gen-${calls}` } }) }; const result = await invokeVisionModel({ imagePath, requestId: 'retry-exhaustion' }); globalThis.fetch = original; assert.equal(calls, 3); assert.equal(result.failureClassification, 'upstream_timeout'); assert.equal(result.retryCount, 2); assert.equal(result.rawResponses.length, 3); restoreEnv() })

test('HTTP 200 malformed assistant content remains malformed_json', async () => { setEnv({ GIGAS_VISION_PROVIDER: 'openrouter', GIGAS_VISION_MODEL: model, GIGAS_VISION_API_KEY: 'secret', GIGAS_VISION_MAX_RETRIES: '0', GIGAS_VISION_CAPABILITY_REFRESH: '1' }); const mock = mockOpenRouter({ metadata: openRouterMetadata(), responseBody: { choices: [{ message: { content: 'not json' } }] } }); const result = await invokeVisionModel({ imagePath, requestId: 'malformed-content' }); mock.restore(); assert.equal(result.failureClassification, 'malformed_json'); assert.equal(result.httpStatus, 200); restoreEnv() })

test('valid HTTP 200 assistant JSON remains a completed result', async () => { setEnv({ GIGAS_VISION_PROVIDER: 'openrouter', GIGAS_VISION_MODEL: model, GIGAS_VISION_API_KEY: 'secret', GIGAS_VISION_MAX_RETRIES: '0', GIGAS_VISION_CAPABILITY_REFRESH: '1' }); const mock = mockOpenRouter({ metadata: openRouterMetadata(), responseBody: { id: 'valid-response', choices: [{ message: { content: '{"ok":true}' } }] } }); const result = await invokeVisionModel({ imagePath, requestId: 'valid-content' }); mock.restore(); assert.equal(result.status, 'completed'); assert.deepEqual(result.parsedOutput, { ok: true }); restoreEnv() })

function mockGemini(responseBody, responseStatus = 200) { const original = globalThis.fetch; const requests = []; globalThis.fetch = async (url, init = {}) => { requests.push({ url, init, payload: init.body ? JSON.parse(init.body) : null }); return new Response(JSON.stringify(responseBody), { status: responseStatus, headers: { 'x-request-id': 'gemini-mock-id' } }) }; return { requests, restore: () => { globalThis.fetch = original } } }
test('Gemini defaults to gemini-3-flash-preview and blocks missing credentials', async () => { setEnv({ GIGAS_VISION_PROVIDER: 'gemini', GIGAS_VISION_MODEL: undefined, GIGAS_VISION_API_KEY: undefined, GEMINI_API_KEY: undefined }); const result = await probeVisionProvider(); assert.equal(result.model, 'gemini-3-flash-preview'); assert.equal(result.usable, false); assert.equal(result.credentialsPresent, false); restoreEnv() })
test('Gemini sends direct image bytes with structured JSON output', async () => { setEnv({ GIGAS_VISION_PROVIDER: 'gemini', GIGAS_VISION_MODEL: undefined, GIGAS_VISION_API_KEY: 'gemini-secret', GIGAS_VISION_MAX_RETRIES: '0' }); const mock = mockGemini({ responseId: 'gemini-response', candidates: [{ content: { parts: [{ text: '{"containsText":true,"lines":[]}' }] } }], usageMetadata: { promptTokenCount: 10, candidatesTokenCount: 5 } }); const result = await invokeVisionModel({ imagePath, prompt: 'Return JSON', schema: { required: ['containsText', 'lines'] }, requestId: 'gemini-success', expectedImageHash: sha256(fs.readFileSync(imagePath)) }); const request = mock.requests[0]; mock.restore(); assert.equal(result.status, 'completed'); assert.equal(result.model, 'gemini-3-flash-preview'); assert.equal(result.responseId, 'gemini-mock-id'); assert.equal(result.usage.promptTokenCount, 10); assert.equal(request.url.includes('key='), false); assert.equal(request.payload.contents[0].parts[1].inline_data.mime_type, 'image/jpeg'); assert.equal(request.payload.generationConfig.responseMimeType, 'application/json'); assert.equal(JSON.stringify(result).includes('gemini-secret'), false); restoreEnv() })
test('Gemini malformed output, 429, timeout, and safety rejection are classified safely', async () => { setEnv({ GIGAS_VISION_PROVIDER: 'gemini', GIGAS_VISION_MODEL: 'gemini-3-flash-preview', GIGAS_VISION_API_KEY: 'gemini-secret', GIGAS_VISION_MAX_RETRIES: '0' }); let mock = mockGemini({ candidates: [{ content: { parts: [{ text: 'not json' }] } }] }); let result = await invokeVisionModel({ imagePath }); mock.restore(); assert.equal(result.failureClassification, 'malformed_json'); assert.ok(result.rawResponseHash || result.rawResponse); mock = mockGemini({ error: { code: 429, message: 'rate limit exceeded' } }, 429); result = await invokeVisionModel({ imagePath }); mock.restore(); assert.equal(result.failureClassification, 'rate_limited'); mock = mockGemini({ error: { code: 400, message: 'safety blocked' } }, 400); result = await invokeVisionModel({ imagePath }); mock.restore(); assert.equal(result.failureClassification, 'provider_safety_rejection'); const original = globalThis.fetch; globalThis.fetch = async () => { const error = new Error('request aborted'); error.name = 'AbortError'; throw error }; result = await invokeVisionModel({ imagePath }); globalThis.fetch = original; assert.equal(result.failureClassification, 'transport_failure'); restoreEnv() })
test('Gemini fallback defaults to gemini-2.5-flash without exposing credentials', () => { setEnv({ GIGAS_VISION_PROVIDER: 'gemini', GIGAS_VISION_MODEL: undefined, GIGAS_VISION_MODEL_2: undefined, GIGAS_VISION_API_KEY: 'secret' }); const result = publicConfig(); assert.deepEqual(result.fallbackModels, ['gemini-2.5-flash']); assert.equal(JSON.stringify(result).includes('secret'), false); restoreEnv() })
test('Gemini compact transcription settings minimize thinking and raise output budget', async () => { setEnv({ GIGAS_VISION_PROVIDER: 'gemini', GIGAS_VISION_MODEL: 'gemini-2.5-flash', GIGAS_VISION_API_KEY: 'gemini-secret', GIGAS_VISION_MAX_RETRIES: '0', GIGAS_VISION_MAX_OUTPUT_TOKENS: '8192', GIGAS_GEMINI_THINKING_BUDGET: '0' }); const mock = mockGemini({ candidates: [{ content: { parts: [{ text: '{"lines":[]}' }] } }] }); const result = await invokeVisionModel({ imagePath, prompt: '{"lines":[{"n":1,"t":"","c":0,"u":false,"i":false,"p":false}]}', schema: { required: ['lines'] }, requestId: 'gemini-compact-settings' }); const request = mock.requests[0]; mock.restore(); assert.equal(result.status, 'completed'); assert.equal(request.payload.generationConfig.responseMimeType, 'application/json'); assert.equal(request.payload.generationConfig.maxOutputTokens, 8192); assert.equal(request.payload.generationConfig.candidateCount, 1); assert.deepEqual(request.payload.generationConfig.thinkingConfig, { thinkingBudget: 0 }); assert.equal(JSON.stringify(request.payload).includes('gemini-secret'), false); restoreEnv() })
test('Gemini 3 minimal level omits thinking budget', async () => { setEnv({ GIGAS_VISION_PROVIDER: 'gemini', GIGAS_VISION_MODEL: 'gemini-3-flash-preview', GIGAS_VISION_API_KEY: 'gemini-secret', GIGAS_VISION_MAX_RETRIES: '0', GIGAS_VISION_MAX_OUTPUT_TOKENS: '8192', GIGAS_GEMINI_THINKING_LEVEL: 'minimal', GIGAS_GEMINI_THINKING_BUDGET: undefined }); const mock = mockGemini({ candidates: [{ content: { parts: [{ text: '{"lines":[]}' }] } }] }); const result = await invokeVisionModel({ imagePath, prompt: 'compact', schema: { required: ['lines'] }, requestId: 'gemini-3-minimal' }); const request = mock.requests[0]; mock.restore(); assert.equal(result.status, 'completed'); assert.deepEqual(request.payload.generationConfig.thinkingConfig, { thinkingLevel: 'minimal' }); assert.equal(JSON.stringify(request.payload).includes('thinkingBudget'), false); restoreEnv() })
