import { registerProfile } from './index.js'

registerProfile({
  id: 'cinematic-bass',
  label: 'Cinematic Bass',
  aliases: ['cinematic bass', 'cinematic', 'orchestral bass'],
  bpmRange: [120, 150],
  preferredScales: ['minor', 'harmonicMinor', 'phrygian', 'dorian'],
  preferredKeys: ['C', 'D', 'E', 'F', 'G', 'A'],
  sectionTemplates: [
    { type: 'intro', lengthBars: 8, energy: 0.1, density: 0.2, tension: 0.1 },
    { type: 'verse', lengthBars: 8, energy: 0.4, density: 0.5, tension: 0.4 },
    { type: 'build', lengthBars: 12, energy: 0.7, density: 0.7, tension: 0.8 },
    { type: 'drop', lengthBars: 16, energy: 0.9, density: 0.85, tension: 0.3 },
    { type: 'break', lengthBars: 8, energy: 0.2, density: 0.25, tension: 0.1 },
    { type: 'build', lengthBars: 12, energy: 0.75, density: 0.75, tension: 0.85 },
    { type: 'drop', lengthBars: 16, energy: 0.95, density: 0.9, tension: 0.2 },
    { type: 'outro', lengthBars: 8, energy: 0.05, density: 0.1, tension: 0 },
  ],
  groove: {
    swing: 0.05,
    shuffle: 0.05,
    kickPattern: 'fourOnFloor',
    hatSubdivision: '8th',
    snarePlacement: '3',
    ghostNoteDensity: 0.05,
    velocityHumanization: 0.2,
    microtimingAmount: 0.03,
  },
  bass: {
    articulationWeights: { growl: 0.3, screech: 0.1, wobble: 0.15, stab: 0.2, sub: 0.25 },
    modulationShapes: ['sine', 'sawtooth', 'square'],
    typicalOctave: 1,
    syncopation: 0.3,
    phraseLength: 4,
  },
  harmony: {
    chordComplexity: 0.85,
    voicingSpread: 'veryWide',
    commonProgressions: ['i-VI-III-VII', 'i-iv-VII-VI', 'III-VII-i-VI', 'i-VII-VI-i'],
    inversionRate: 0.5,
    susRate: 0.35,
  },
  melody: {
    density: 0.4,
    noteLength: '8th',
    octaveRange: [4, 7],
    repetitionRate: 0.25,
    callResponse: true,
    restProbability: 0.1,
  },
  transitions: {
    riserLength: 8,
    impactFrequency: 'drop',
    drumFillRate: 0.3,
    silenceBeforeDrop: true,
    filterSweepRate: 0.8,
    fakeoutRate: 0.05,
  },
  energy: {
    typicalCurve: 'buildRelease',
    maxEnergy: 1,
    minEnergy: 0.05,
    dropContrast: 0.6,
  },
  soundPalette: {
    bassType: 'growl',
    leadType: 'synth',
    padType: 'orchestral',
    kickType: 'heavy',
    snareType: 'layered',
    hatType: 'tight',
  },
})
