import { registerProfile } from './index.js'

registerProfile({
  id: 'drum-and-bass',
  label: 'Drum and Bass',
  aliases: ['drum and bass', 'dnb', 'd&b', 'drum & bass'],
  bpmRange: [170, 180],
  preferredScales: ['minor', 'dorian', 'major'],
  preferredKeys: ['C', 'D', 'E', 'F', 'G', 'A'],
  sectionTemplates: [
    { type: 'intro', lengthBars: 8, energy: 0.15, density: 0.3, tension: 0.1 },
    { type: 'verse', lengthBars: 16, energy: 0.5, density: 0.6, tension: 0.3 },
    { type: 'build', lengthBars: 8, energy: 0.7, density: 0.7, tension: 0.7 },
    { type: 'drop', lengthBars: 16, energy: 0.95, density: 0.9, tension: 0.3 },
    { type: 'break', lengthBars: 8, energy: 0.2, density: 0.2, tension: 0.1 },
    { type: 'build', lengthBars: 8, energy: 0.7, density: 0.7, tension: 0.8 },
    { type: 'drop', lengthBars: 16, energy: 0.98, density: 0.95, tension: 0.2 },
    { type: 'outro', lengthBars: 8, energy: 0.1, density: 0.2, tension: 0 },
  ],
  groove: {
    swing: 0.1,
    shuffle: 0.2,
    kickPattern: 'dnb',
    hatSubdivision: '32nd',
    snarePlacement: '2_4',
    ghostNoteDensity: 0.3,
    velocityHumanization: 0.2,
    microtimingAmount: 0.08,
  },
  bass: {
    articulationWeights: { growl: 0.1, screech: 0.05, wobble: 0.1, stab: 0.15, sub: 0.6 },
    modulationShapes: ['sine', 'triangle'],
    typicalOctave: 1,
    syncopation: 0.7,
    phraseLength: 4,
  },
  harmony: {
    chordComplexity: 0.5,
    voicingSpread: 'medium',
    commonProgressions: ['i-VI-III-VII', 'i-iv-VII-VI', 'ii-V-i', 'i-VII-VI-V'],
    inversionRate: 0.3,
    susRate: 0.2,
  },
  melody: {
    density: 0.4,
    noteLength: '16th',
    octaveRange: [4, 6],
    repetitionRate: 0.35,
    callResponse: true,
    restProbability: 0.12,
  },
  transitions: {
    riserLength: 4,
    impactFrequency: 'drop',
    drumFillRate: 0.6,
    silenceBeforeDrop: false,
    filterSweepRate: 0.5,
    fakeoutRate: 0.08,
  },
  energy: {
    typicalCurve: 'rolling',
    maxEnergy: 1,
    minEnergy: 0.05,
    dropContrast: 0.4,
  },
  soundPalette: {
    bassType: 'sub',
    leadType: 'synth',
    padType: 'atmospheric',
    kickType: 'punchy',
    snareType: 'tight',
    hatType: 'clean',
  },
})
