import { registerProfile } from './index.js'

registerProfile({
  id: 'dubstep',
  label: 'Dubstep',
  aliases: ['dubstep', 'brostep'],
  bpmRange: [140, 150],
  preferredScales: ['minor', 'dorian', 'phrygian'],
  preferredKeys: ['D', 'F', 'G', 'A'],
  sectionTemplates: [
    { type: 'intro', lengthBars: 8, energy: 0.2, density: 0.3, tension: 0.1 },
    { type: 'build', lengthBars: 8, energy: 0.5, density: 0.5, tension: 0.7 },
    { type: 'drop', lengthBars: 16, energy: 0.9, density: 0.9, tension: 0.3 },
    { type: 'break', lengthBars: 8, energy: 0.3, density: 0.2, tension: 0.1 },
    { type: 'build', lengthBars: 8, energy: 0.6, density: 0.6, tension: 0.8 },
    { type: 'drop', lengthBars: 16, energy: 0.95, density: 0.95, tension: 0.2 },
    { type: 'outro', lengthBars: 4, energy: 0.1, density: 0.2, tension: 0 },
  ],
  groove: {
    swing: 0,
    shuffle: 0,
    kickPattern: 'halfTime',
    hatSubdivision: '16th',
    snarePlacement: '3',
    ghostNoteDensity: 0.1,
    velocityHumanization: 0.15,
    microtimingAmount: 0.05,
  },
  bass: {
    articulationWeights: { growl: 0.4, screech: 0.15, wobble: 0.3, stab: 0.1, sub: 0.05 },
    modulationShapes: ['sine', 'square', 'sawtooth'],
    typicalOctave: 2,
    syncopation: 0.6,
    phraseLength: 2,
  },
  harmony: {
    chordComplexity: 0.6,
    voicingSpread: 'wide',
    commonProgressions: ['i-VI-III-VII', 'i-VII-VI-VII', 'i-iv-VII-VI'],
    inversionRate: 0.3,
    susRate: 0.2,
  },
  melody: {
    density: 0.3,
    noteLength: '16th',
    octaveRange: [4, 6],
    repetitionRate: 0.4,
    callResponse: true,
    restProbability: 0.15,
  },
  transitions: {
    riserLength: 4,
    impactFrequency: 'drop',
    drumFillRate: 0.5,
    silenceBeforeDrop: true,
    filterSweepRate: 0.7,
    fakeoutRate: 0.1,
  },
  energy: {
    typicalCurve: 'stepUp',
    maxEnergy: 1,
    minEnergy: 0.05,
    dropContrast: 0.6,
  },
  soundPalette: {
    bassType: 'wobble',
    leadType: 'screech',
    padType: 'atmospheric',
    kickType: 'distorted',
    snareType: 'layered',
    hatType: 'tight',
  },
})
