import { registerProfile } from './index.js'

registerProfile({
  id: 'experimental-bass',
  label: 'Experimental Bass',
  aliases: ['experimental bass', 'experimental', 'bass music'],
  bpmRange: [130, 170],
  preferredScales: ['minor', 'phrygian', 'wholeTone', 'diminished', 'augmented'],
  preferredKeys: ['C', 'D', 'E', 'F', 'G', 'A', 'A#', 'D#'],
  sectionTemplates: [
    { type: 'intro', lengthBars: 8, energy: 0.1, density: 0.15, tension: 0.1 },
    { type: 'verse', lengthBars: 12, energy: 0.4, density: 0.4, tension: 0.4 },
    { type: 'build', lengthBars: 10, energy: 0.65, density: 0.6, tension: 0.75 },
    { type: 'drop', lengthBars: 16, energy: 0.9, density: 0.85, tension: 0.3 },
    { type: 'break', lengthBars: 10, energy: 0.2, density: 0.2, tension: 0.1 },
    { type: 'build', lengthBars: 10, energy: 0.7, density: 0.65, tension: 0.8 },
    { type: 'drop', lengthBars: 16, energy: 0.95, density: 0.9, tension: 0.25 },
    { type: 'outro', lengthBars: 8, energy: 0.05, density: 0.1, tension: 0 },
  ],
  groove: {
    swing: 0.15,
    shuffle: 0.15,
    kickPattern: 'polyrhythm',
    hatSubdivision: '32nd',
    snarePlacement: '3',
    ghostNoteDensity: 0.2,
    velocityHumanization: 0.25,
    microtimingAmount: 0.12,
  },
  bass: {
    articulationWeights: { growl: 0.35, screech: 0.2, wobble: 0.2, stab: 0.15, sub: 0.1 },
    modulationShapes: ['sine', 'square', 'sawtooth', 'random'],
    typicalOctave: 2,
    syncopation: 0.8,
    phraseLength: 2,
  },
  harmony: {
    chordComplexity: 0.9,
    voicingSpread: 'wide',
    commonProgressions: ['i-VII-VI-VII', 'i-III-VII-VI', 'i-iv-VI-V', 'i-VI-iv-VII'],
    inversionRate: 0.5,
    susRate: 0.4,
  },
  melody: {
    density: 0.3,
    noteLength: '16th',
    octaveRange: [3, 6],
    repetitionRate: 0.2,
    callResponse: true,
    restProbability: 0.2,
  },
  transitions: {
    riserLength: 6,
    impactFrequency: 'drop',
    drumFillRate: 0.5,
    silenceBeforeDrop: true,
    filterSweepRate: 0.7,
    fakeoutRate: 0.25,
  },
  energy: {
    typicalCurve: 'irregular',
    maxEnergy: 1,
    minEnergy: 0.05,
    dropContrast: 0.6,
  },
  soundPalette: {
    bassType: 'growl',
    leadType: 'screech',
    padType: 'textural',
    kickType: 'distorted',
    snareType: 'layered',
    hatType: 'bright',
  },
})
