import { registerProfile } from './index.js'

registerProfile({
  id: 'melodic-dubstep',
  label: 'Melodic Dubstep',
  aliases: ['melodic dubstep', 'melodic'],
  bpmRange: [140, 150],
  preferredScales: ['minor', 'major', 'dorian', 'lydian'],
  preferredKeys: ['C', 'G', 'D', 'E', 'F', 'A'],
  sectionTemplates: [
    { type: 'intro', lengthBars: 8, energy: 0.15, density: 0.2, tension: 0.05 },
    { type: 'verse', lengthBars: 8, energy: 0.3, density: 0.4, tension: 0.2 },
    { type: 'build', lengthBars: 8, energy: 0.6, density: 0.6, tension: 0.7 },
    { type: 'drop', lengthBars: 16, energy: 0.9, density: 0.85, tension: 0.3 },
    { type: 'break', lengthBars: 8, energy: 0.25, density: 0.3, tension: 0.1 },
    { type: 'build', lengthBars: 8, energy: 0.7, density: 0.7, tension: 0.8 },
    { type: 'drop', lengthBars: 16, energy: 0.95, density: 0.9, tension: 0.2 },
    { type: 'outro', lengthBars: 8, energy: 0.1, density: 0.15, tension: 0 },
  ],
  groove: {
    swing: 0.05,
    shuffle: 0.05,
    kickPattern: 'halfTime',
    hatSubdivision: '16th',
    snarePlacement: '3',
    ghostNoteDensity: 0.08,
    velocityHumanization: 0.12,
    microtimingAmount: 0.04,
  },
  bass: {
    articulationWeights: { growl: 0.2, screech: 0.05, wobble: 0.3, stab: 0.15, sub: 0.3 },
    modulationShapes: ['sine', 'triangle', 'sawtooth'],
    typicalOctave: 2,
    syncopation: 0.4,
    phraseLength: 4,
  },
  harmony: {
    chordComplexity: 0.8,
    voicingSpread: 'wide',
    commonProgressions: ['i-VI-III-VII', 'i-iv-VII-VI', 'VI-III-VII-i', 'i-VII-VI-V'],
    inversionRate: 0.4,
    susRate: 0.3,
  },
  melody: {
    density: 0.5,
    noteLength: '16th',
    octaveRange: [4, 7],
    repetitionRate: 0.3,
    callResponse: true,
    restProbability: 0.1,
  },
  transitions: {
    riserLength: 4,
    impactFrequency: 'drop',
    drumFillRate: 0.3,
    silenceBeforeDrop: true,
    filterSweepRate: 0.6,
    fakeoutRate: 0.05,
  },
  energy: {
    typicalCurve: 'buildRelease',
    maxEnergy: 1,
    minEnergy: 0.05,
    dropContrast: 0.5,
  },
  soundPalette: {
    bassType: 'sub',
    leadType: 'synth',
    padType: 'ambient',
    kickType: 'punchy',
    snareType: 'layered',
    hatType: 'clean',
  },
})
