import { registerProfile } from './index.js'

registerProfile({
  id: 'riddim',
  label: 'Riddim',
  aliases: ['riddim', 'riddim dubstep'],
  bpmRange: [140, 150],
  preferredScales: ['minor', 'phrygian', 'dorian'],
  preferredKeys: ['D', 'F', 'G', 'A#'],
  sectionTemplates: [
    { type: 'intro', lengthBars: 8, energy: 0.2, density: 0.2, tension: 0.1 },
    { type: 'build', lengthBars: 8, energy: 0.5, density: 0.4, tension: 0.6 },
    { type: 'drop', lengthBars: 16, energy: 0.95, density: 0.95, tension: 0.2 },
    { type: 'break', lengthBars: 8, energy: 0.3, density: 0.2, tension: 0.1 },
    { type: 'build', lengthBars: 8, energy: 0.6, density: 0.5, tension: 0.7 },
    { type: 'drop', lengthBars: 16, energy: 0.98, density: 0.98, tension: 0.15 },
    { type: 'outro', lengthBars: 4, energy: 0.1, density: 0.15, tension: 0 },
  ],
  groove: {
    swing: 0,
    shuffle: 0.1,
    kickPattern: 'halfTime',
    hatSubdivision: '16th',
    snarePlacement: '3',
    ghostNoteDensity: 0.15,
    velocityHumanization: 0.1,
    microtimingAmount: 0.03,
  },
  bass: {
    articulationWeights: { growl: 0.5, screech: 0.05, wobble: 0.35, stab: 0.08, sub: 0.02 },
    modulationShapes: ['square', 'sawtooth', 'sine'],
    typicalOctave: 2,
    syncopation: 0.7,
    phraseLength: 1,
  },
  harmony: {
    chordComplexity: 0.3,
    voicingSpread: 'wide',
    commonProgressions: ['i-VII-VI-VII', 'i-III-VII-VI', 'i-VI-VII-i'],
    inversionRate: 0.2,
    susRate: 0.1,
  },
  melody: {
    density: 0.2,
    noteLength: '8th',
    octaveRange: [4, 5],
    repetitionRate: 0.6,
    callResponse: true,
    restProbability: 0.2,
  },
  transitions: {
    riserLength: 4,
    impactFrequency: 'drop',
    drumFillRate: 0.4,
    silenceBeforeDrop: true,
    filterSweepRate: 0.8,
    fakeoutRate: 0.15,
  },
  energy: {
    typicalCurve: 'stepUp',
    maxEnergy: 1,
    minEnergy: 0.05,
    dropContrast: 0.7,
  },
  soundPalette: {
    bassType: 'growl',
    leadType: 'growl',
    padType: 'minimal',
    kickType: 'distorted',
    snareType: 'tight',
    hatType: 'tight',
  },
})
