import { registerProfile } from './index.js'

registerProfile({
  id: 'trap',
  label: 'Trap',
  aliases: ['trap', 'trap music'],
  bpmRange: [130, 160],
  preferredScales: ['minor', 'dorian', 'phrygian'],
  preferredKeys: ['C', 'D', 'E', 'F', 'G', 'A', 'A#'],
  sectionTemplates: [
    { type: 'intro', lengthBars: 8, energy: 0.15, density: 0.2, tension: 0.1 },
    { type: 'verse', lengthBars: 16, energy: 0.5, density: 0.5, tension: 0.3 },
    { type: 'build', lengthBars: 8, energy: 0.6, density: 0.5, tension: 0.6 },
    { type: 'drop', lengthBars: 16, energy: 0.9, density: 0.8, tension: 0.2 },
    { type: 'break', lengthBars: 8, energy: 0.25, density: 0.2, tension: 0.1 },
    { type: 'build', lengthBars: 8, energy: 0.7, density: 0.6, tension: 0.7 },
    { type: 'drop', lengthBars: 16, energy: 0.95, density: 0.85, tension: 0.15 },
    { type: 'outro', lengthBars: 4, energy: 0.1, density: 0.15, tension: 0 },
  ],
  groove: {
    swing: 0.15,
    shuffle: 0.1,
    kickPattern: 'trap',
    hatSubdivision: '32nd',
    snarePlacement: '3',
    ghostNoteDensity: 0.25,
    velocityHumanization: 0.2,
    microtimingAmount: 0.1,
  },
  bass: {
    articulationWeights: { growl: 0.1, screech: 0.05, wobble: 0.1, stab: 0.15, sub: 0.6 },
    modulationShapes: ['sine', 'triangle'],
    typicalOctave: 1,
    syncopation: 0.5,
    phraseLength: 2,
  },
  harmony: {
    chordComplexity: 0.4,
    voicingSpread: 'medium',
    commonProgressions: ['i-VII-VI-VII', 'i-iv-VII', 'VI-VII-i', 'i-III-VII-VI'],
    inversionRate: 0.3,
    susRate: 0.25,
  },
  melody: {
    density: 0.35,
    noteLength: '8th',
    octaveRange: [4, 6],
    repetitionRate: 0.4,
    callResponse: true,
    restProbability: 0.15,
  },
  transitions: {
    riserLength: 4,
    impactFrequency: 'drop',
    drumFillRate: 0.4,
    silenceBeforeDrop: true,
    filterSweepRate: 0.5,
    fakeoutRate: 0.2,
  },
  energy: {
    typicalCurve: 'stepUp',
    maxEnergy: 1,
    minEnergy: 0.05,
    dropContrast: 0.5,
  },
  soundPalette: {
    bassType: 'sub',
    leadType: 'synth',
    padType: 'dark',
    kickType: 'heavy',
    snareType: 'layered',
    hatType: 'bright',
  },
})
