import { registerProfile } from './index.js'

registerProfile({
  id: 'wave',
  label: 'Wave',
  aliases: ['wave', 'wave music', 'wavemusic'],
  bpmRange: [130, 150],
  preferredScales: ['minor', 'phrygian', 'dorian', 'harmonicMinor'],
  preferredKeys: ['C', 'D', 'E', 'F', 'G', 'A'],
  sectionTemplates: [
    { type: 'intro', lengthBars: 8, energy: 0.1, density: 0.15, tension: 0.05 },
    { type: 'verse', lengthBars: 16, energy: 0.4, density: 0.4, tension: 0.3 },
    { type: 'build', lengthBars: 8, energy: 0.6, density: 0.5, tension: 0.7 },
    { type: 'drop', lengthBars: 16, energy: 0.85, density: 0.75, tension: 0.3 },
    { type: 'break', lengthBars: 8, energy: 0.15, density: 0.15, tension: 0.05 },
    { type: 'build', lengthBars: 8, energy: 0.65, density: 0.55, tension: 0.75 },
    { type: 'drop', lengthBars: 16, energy: 0.9, density: 0.8, tension: 0.25 },
    { type: 'outro', lengthBars: 8, energy: 0.05, density: 0.1, tension: 0 },
  ],
  groove: {
    swing: 0.08,
    shuffle: 0.05,
    kickPattern: 'halfTime',
    hatSubdivision: '16th',
    snarePlacement: '3',
    ghostNoteDensity: 0.1,
    velocityHumanization: 0.15,
    microtimingAmount: 0.05,
  },
  bass: {
    articulationWeights: { growl: 0.15, screech: 0.1, wobble: 0.2, stab: 0.2, sub: 0.35 },
    modulationShapes: ['sine', 'triangle', 'sawtooth'],
    typicalOctave: 2,
    syncopation: 0.4,
    phraseLength: 4,
  },
  harmony: {
    chordComplexity: 0.7,
    voicingSpread: 'wide',
    commonProgressions: ['i-VI-III-VII', 'i-iv-VI-VII', 'VI-III-VII-i'],
    inversionRate: 0.4,
    susRate: 0.3,
  },
  melody: {
    density: 0.3,
    noteLength: '8th',
    octaveRange: [4, 6],
    repetitionRate: 0.3,
    callResponse: true,
    restProbability: 0.15,
  },
  transitions: {
    riserLength: 8,
    impactFrequency: 'drop',
    drumFillRate: 0.2,
    silenceBeforeDrop: true,
    filterSweepRate: 0.6,
    fakeoutRate: 0.05,
  },
  energy: {
    typicalCurve: 'buildRelease',
    maxEnergy: 0.95,
    minEnergy: 0.05,
    dropContrast: 0.5,
  },
  soundPalette: {
    bassType: 'sub',
    leadType: 'synth',
    padType: 'atmospheric',
    kickType: 'punchy',
    snareType: 'tight',
    hatType: 'clean',
  },
})
