import { formatCitation, getAuthoritiesForFolio, getCitationsForFolio, getLicenseById, formatAttribution } from '../data/provenance.js'
import { VERIFICATION_LABELS } from '../data/verification.js'

export class SourcePanel {
  constructor({ root, onClose }) { this.root = root; this.panel = root.querySelector('#source-panel'); this.onClose = onClose; this.returnTarget = null }
  open(folio) { this.returnTarget = document.activeElement; const sources = Object.entries(folio.sources || {}); this.panel.innerHTML = `<div class="source-panel-header"><h2 id="source-panel-title">Sources for ${folio.folioNumber}</h2><button id="close-source-panel" type="button" aria-label="Close source information">×</button></div><p class="source-uncertainty">${folio.verificationState === 'placeholder' ? 'Placeholder record: this material is not presented as verified historical evidence.' : 'Review each layer separately; provenance does not make editorial content primary-source material.'}</p><dl class="source-record"><dt>Folio</dt><dd>${folio.id} · ${folio.section} · ${folio.chapter}</dd><dt>Verification</dt><dd><span class="verification-badge status-${folio.verificationState}"><i aria-hidden="true"></i>${VERIFICATION_LABELS[folio.verificationState] || folio.verificationState}</span></dd></dl><div class="source-layers">${sources.map(([layer, source]) => this.renderLayer(layer, source, folio)).join('')}</div><div class="source-actions"><button id="copy-citations" type="button">Copy citations</button><span id="source-status" role="status" aria-live="polite"></span></div>`; this.panel.hidden = false; this.panel.setAttribute('aria-modal', 'true'); this.panel.querySelector('#close-source-panel').addEventListener('click', () => this.close()); this.root.addEventListener('keydown', this.handleKey); this.panel.querySelector('#copy-citations')?.addEventListener('click', () => this.copyCitations(folio)); this.panel.querySelector('#close-source-panel').focus() }
  renderLayer(layer, source, folio) { const citations = getCitationsForFolio(folio, layer); const authorities = getAuthoritiesForFolio(folio, layer); const license = getLicenseById(source.licenseId); const history = folio.verificationHistory || []; return `<section class="source-layer"><h3>${folio.classifications?.[layer] || layer}</h3><p><strong>State:</strong> ${VERIFICATION_LABELS[source.verificationState] || source.verificationState}</p><p><strong>Authorities:</strong> ${authorities.map((item) => item.name).join(', ') || 'Unassigned'}</p><p><strong>License:</strong> ${license?.shortName || 'Unknown'}${license && !license.allowsOfflineCaching ? ' · offline caching restricted' : ''}</p>${citations.length ? `<ul>${citations.map((citation) => `<li>${formatCitation(citation)}</li>`).join('')}</ul>` : '<p>No citation recorded.</p>'}${history.length ? `<details><summary>Verification history</summary><ul>${history.map((item) => `<li>${item.state} · ${item.reviewedAt || 'undated'}${item.notes ? ` · ${item.notes}` : ''}</li>`).join('')}</ul></details>` : ''}${license ? `<small>${formatAttribution(license)}</small>` : ''}</section>` }
  async copyCitations(folio) { const text = Object.values(folio.sources || {}).flatMap((source) => getCitationsForFolio(folio, Object.keys(folio.sources).find((key) => folio.sources[key] === source))).map(formatCitation).filter(Boolean).join('\n'); try { await navigator.clipboard.writeText(text); this.root.querySelector('#source-status').textContent = 'Citations copied.' } catch { const area = document.createElement('textarea'); area.value = text; document.body.append(area); area.select(); document.execCommand('copy'); area.remove(); this.root.querySelector('#source-status').textContent = 'Citations copied.' } }
  close() { this.panel.hidden = true; this.panel.removeAttribute('aria-modal'); this.root.removeEventListener('keydown', this.handleKey); this.returnTarget?.focus(); this.onClose?.() }
  handleKey = (event) => { if (event.key === 'Escape') return this.close(); if (event.key !== 'Tab') return; const focusable = [...this.panel.querySelectorAll('button, [href], summary')]; const first = focusable[0]; const last = focusable.at(-1); if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus() } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus() } }
}
