import { openCodexDB } from '../storage/codex-db.js'
import { createDraftSession } from './canonical-data.js'
import { getCanonicalFingerprint } from './fingerprint.js'

const modes = { transcription:'Diplomatic transcription', expansion:'Abbreviation expansion', literal:'Literal English', readable:'Readable English', alignment:'Alignment workbench', review:'Reviewer mode' }
export async function renderEditorialWorkspace(root, mode = '') { const db = await openCodexDB(); const fingerprint = await getCanonicalFingerprint(); let session = await db.getSession(); const stale = session && session.baseRevision && session.baseRevision !== fingerprint; if (!session || session.folioId !== 'folio-002r') { session = createDraftSession(fingerprint); await db.saveSession(session) } root.innerHTML = `<main class="editorial-tool workspace" aria-labelledby="workspace-title"><p class="eyebrow">Project GIGAS · editorial workbench</p><h1 id="workspace-title">Folio 2r editorial workspace</h1><p>Canonical repository data is read-only here. Local draft sessions are stored in IndexedDB and exported as candidates.</p>${stale ? '<p class="workspace-warning" role="alert">This local session was created against an older canonical revision. Review the fingerprint before export.</p>' : ''}<dl class="session-summary"><dt>Session</dt><dd>${session.id}</dd><dt>Base fingerprint</dt><dd><code>${session.baseRevision || fingerprint}</code></dd><dt>Status</dt><dd>${session.status} · ${session.dirty ? 'dirty' : 'clean'}</dd></dl><nav class="workspace-tabs" aria-label="Editorial workbench sections"><a href="/editor/folio-002r/regions">Regions</a><a href="/editor/folio-002r/transcription">Transcription</a><a href="/editor/folio-002r/expansion">Expansion</a><a href="/editor/folio-002r/literal">Literal English</a><a href="/editor/folio-002r/readable">Readable English</a><a href="/editor/folio-002r/alignment">Alignment</a><a href="/editor/folio-002r/review">Review</a><a href="/editor/folio-002r/compare">Compare</a><a href="/editor/folio-002r/evidence">Evidence view</a><a href="/editorial-status">Status</a></nav><section class="workspace-panel"><h2>${modes[mode] || 'Workflow overview'}</h2>${mode === 'transcription' ? blockedText('Diplomatic transcription') : mode === 'expansion' ? blockedText('Abbreviation expansion') : mode === 'literal' ? blockedText('Literal English') : mode === 'readable' ? blockedText('Readable English') : mode === 'alignment' ? blockedText('Alignment') : mode === 'review' ? reviewText() : overviewText()}</section><p><a href="/">Return to reader</a></p></main>`; if (stale) { const acknowledge = document.createElement('button'); acknowledge.type = 'button'; acknowledge.textContent = 'Start a fresh session'; acknowledge.addEventListener('click', async () => { const next = createDraftSession(fingerprint); await db.saveSession(next); location.reload() }); root.querySelector('.workspace-warning').append(acknowledge) } }
function blockedText(label) { return `<p class="workspace-blocked"><strong>${label} is blocked.</strong> Canonical 2r records are empty because no qualified human transcription has been supplied. This panel accepts candidate data only after source, contributor, and review metadata are present.</p><p>Use the blank template: <code>npm run export:transcription-template -- --folio=002r</code>.</p>` }
function reviewText() { return '<p>Reviewer mode loads canonical data and candidate packages without mutating either. The current canonical state has one open blocking source finding.</p><a href="/editor/folio-002r/compare">Open comparison</a>' }
function overviewText() { return '<ul><li>Image/catalog provenance: recorded</li><li>Draft layout guides: available</li><li>Canonical transcription: empty</li><li>Translations: empty</li><li>Release state: blocked</li></ul><p>Begin with region authoring, then import a genuine human transcription candidate.</p>' }
