import fs from 'node:fs'
import path from 'node:path'
const root = path.resolve(import.meta.dirname, '..'); const folio = new URLSearchParams(process.argv.slice(2).join('&')).get('folio') || process.argv.find((arg) => arg.startsWith('--folio='))?.split('=')[1]; const target = folio === '002r' ? '002r' : null
if (!target) { console.error('ERROR: provide --folio=002r; only the licensed 2r fixture is configured.'); process.exit(1) }
const license = JSON.parse(fs.readFileSync(path.join(root, 'src/data/licenses.json'))).find((item) => item.id === 'license-cc-by-4-0'); if (!license?.allowsModification) { console.error('ERROR: tile generation blocked because the source license does not allow modification.'); process.exit(1) }
const output = path.join(root, 'public/tiles/real/002r'); const manifest = path.join(output, 'manifest.json'); if (!fs.existsSync(manifest)) { console.error('ERROR: tile manifest is missing; no output will be created.'); process.exit(1) }
const force = process.argv.includes('--force'); const existing = fs.readdirSync(output, { recursive: true }).filter((item) => item.endsWith('.jpg')); if (existing.length && !force) { console.error('ERROR: tile output already exists; use --force only to regenerate this controlled fixture.'); process.exit(1) }
const image = 'https://iiif.manuscripta.se/iiif/ms-100500/ms-100500_0003.tif'; for (let z = 0; z < 3; z += 1) { const n = 2 ** z; const size = 2048 / n; fs.mkdirSync(path.join(output, String(z)), { recursive: true }); for (let x = 0; x < n; x += 1) for (let y = 0; y < n; y += 1) { const url = `${image}/${x * size},${y * size},${size},${size}/256,/0/default.jpg`; const response = await fetch(url); if (!response.ok) throw new Error(`Tile request failed: ${response.status} ${url}`); fs.writeFileSync(path.join(output, String(z), `${x}-${y}.jpg`), Buffer.from(await response.arrayBuffer())) } }
console.log('Generated the controlled 002r tile fixture. Run npm run verify:assets -- --write afterward to refresh checksums.')
