import fs from 'node:fs'
import path from 'node:path'
import { parseArgs, root, sha256 } from '../src/manuscript/source-ingestion.js'
import { invokeVisionModelSafe } from '../src/manuscript/vision-provider-runtime.js'
import { loadJob, jobDirectory, batchRoot, batchPolicy, atomicJson, mergeRegionCandidates, writePageCandidate } from '../src/manuscript/batch-pipeline.js'
import { compactRegionPrompt, compactRegionSchema, extractAssistant, parseSalvage, normalizeSalvage, classifyFailure } from '../src/manuscript/batch-recovery.js'

const args = parseArgs(process.argv.slice(2)); const originalJobId = args.job; const original = loadJob(originalJobId); const recoveryId = `recovery-${new Date().toISOString().replace(/[:.]/g, '-')}-${process.pid}`; const recoveryDir = path.join(batchRoot, recoveryId); fs.mkdirSync(recoveryDir, { recursive: true })
const provider = process.env.GIGAS_VISION_PROVIDER || original.provider || 'openrouter'; const primary = process.env.GIGAS_VISION_MODEL || (provider === 'gemini' ? 'gemini-3-flash-preview' : original.model || 'google/gemma-4-26b-a4b-it:free'); const fallbacks = (provider === 'gemini' ? ['gemini-2.5-flash'] : ['google/gemma-4-31b-it:free', 'google/gemma-3-27b-it:free', 'google/gemma-3-4b-it:free']).filter((m) => m !== primary)
const practicalSchema = compactRegionSchema
const prompt = compactRegionPrompt
function json(file, value) { atomicJson(file, value) }
function regionDir(page, regionId) { return path.join(jobDirectory(originalJobId), `pages/page-${String(page).padStart(4, '0')}/regions`, regionId) }
function readRawCandidate(dir) { const file = path.join(dir, 'raw-response.txt'); if (!fs.existsSync(file)) return null; const raw = fs.readFileSync(file, 'utf8'); const { content } = extractAssistant(raw); const parsed = parseSalvage(content); return { raw, parsed } }
function identityFromRegion(file) { return JSON.parse(fs.readFileSync(file, 'utf8')) }
function previouslyRecoveredRegionIds() { const ids = new Set(); if (!fs.existsSync(batchRoot)) return ids; for (const entry of fs.readdirSync(batchRoot, { withFileTypes: true })) { if (!entry.isDirectory() || !entry.name.startsWith('recovery-')) continue; const recovered = path.join(batchRoot, entry.name, 'recovered'); if (!fs.existsSync(recovered)) continue; for (const page of fs.readdirSync(recovered, { withFileTypes: true })) { if (!page.isDirectory()) continue; const pageDir = path.join(recovered, page.name); for (const region of fs.readdirSync(pageDir, { withFileTypes: true })) if (region.isDirectory() && fs.existsSync(path.join(pageDir, region.name, 'candidate.json'))) ids.add(region.name) } } return ids }
function persistAttempt(dir, attempt, model, result) { const target = path.join(recoveryDir, 'attempts', path.basename(dir), `attempt-${String(attempt).padStart(2, '0')}`); fs.mkdirSync(target, { recursive: true }); if (result.rawResponse) fs.writeFileSync(path.join(target, 'raw-response.txt'), result.rawResponse); json(path.join(target, 'result.json'), { ...result, rawResponse: result.rawResponse ? '[see raw-response.txt]' : '', requestedModel: model }); return target }
async function retryRegion(page, failure) {
  const dir = regionDir(page, failure.regionId); const region = identityFromRegion(path.join(dir, 'region.json')); const crop = path.join(dir, 'crop.jpg'); const results = []; let attempt = 0
  for (const model of [primary, fallbacks[0]].slice(0, 2)) { attempt++; process.env.GIGAS_VISION_MODEL = model; process.env.GIGAS_VISION_MAX_RETRIES = '0'; process.env.GIGAS_VISION_MAX_OUTPUT_TOKENS = '8192'; process.env.GIGAS_GEMINI_THINKING_LEVEL = 'minimal'; delete process.env.GIGAS_GEMINI_THINKING_BUDGET; const result = await invokeVisionModelSafe({ imagePath: crop, expectedImageHash: region.crop?.sha256, prompt, schema: practicalSchema, requestId: `${recoveryId}-${region.regionId}-attempt-${attempt}`, timeoutMs: Number(process.env.GIGAS_RECOVERY_TIMEOUT_MS || 180000) }); const parsed = result.parsedOutput || (result.rawResponse ? parseSalvage(extractAssistant(result.rawResponse).content).parsed : null); const normalized = parsed ? normalizeSalvage(parsed, region) : null; results.push({ attempt, model, result }); persistAttempt(dir, attempt, model, { ...result, parsedOutput: parsed, partialResponse: Boolean(parsed?.partialResponse), truncated: Boolean(parsed?.truncated) }); if (normalized?.candidate) return { status: normalized.candidate.partialResponse ? 'recovered_partial' : 'recovered_by_retry', candidate: normalized.candidate, attempts: results, repairs: normalized.repairs, findings: normalized.findings } }
  return { status: 'still_failed', attempts: results, failureClassification: results.at(-1)?.result?.failureClassification || 'provider_error' }
}

async function main() {
  const priorRecovered = previouslyRecoveredRegionIds(); const allFailures = original.pages.flatMap((page) => page.failures.map((failure) => ({ page: page.page, ...failure }))); const failures = allFailures.filter((failure) => !priorRecovered.has(failure.regionId)); const skippedPreviouslyUsable = allFailures.length - failures.length; const categories = {}; const salvaged = []; const recovered = []; const stillFailed = []; const pageCandidates = new Map()
  for (let failureIndex = 0; failureIndex < failures.length; failureIndex++) { const failure = failures[failureIndex]; const category = classifyFailure(failure); categories[category] = (categories[category] || 0) + 1; const dir = regionDir(failure.page, failure.regionId); const raw = readRawCandidate(dir); const region = identityFromRegion(path.join(dir, 'region.json')); if (raw?.parsed?.parsed) { const normalized = normalizeSalvage(raw.parsed.parsed, region); if (normalized.candidate) { const out = path.join(recoveryDir, 'salvaged', `page-${failure.page}`, failure.regionId); fs.mkdirSync(out, { recursive: true }); fs.copyFileSync(path.join(dir, 'raw-response.txt'), path.join(out, 'raw-response.txt')); json(path.join(out, 'candidate.json'), normalized.candidate); json(path.join(out, 'normalization.json'), { status: 'structurally_salvaged', repairs: normalized.repairs, findings: normalized.findings, rawResponseHash: sha256(Buffer.from(raw.raw)), canonical: false, reviewRequired: true }); salvaged.push({ ...failure, category, repairs: normalized.repairs }); continue } }
    const result = await retryRegion(failure.page, failure); if (result.status === 'recovered_by_retry' || result.status === 'recovered_partial') { const out = path.join(recoveryDir, 'recovered', `page-${failure.page}`, failure.regionId); fs.mkdirSync(out, { recursive: true }); json(path.join(out, 'candidate.json'), result.candidate); json(path.join(out, 'recovery.json'), { status: result.status, attempts: result.attempts.map((a) => ({ attempt: a.attempt, requestedModel: a.model, actualRoutedModel: a.result.actualRoutedModel, responseId: a.result.responseId || null, rawResponseHash: a.result.rawProviderResponseHash || null, failureClassification: a.result.failureClassification || null })), repairs: result.repairs, findings: result.findings, canonical: false }); recovered.push({ ...failure, category, model: result.attempts.at(-1).model, partial: result.status === 'recovered_partial' }); } else stillFailed.push({ ...failure, category, failureClassification: result.failureClassification }); if (failureIndex < failures.length - 1) await new Promise((resolve) => setTimeout(resolve, 2000)) }
  // Rebuild page candidates from original valid candidates plus recovery outputs.
  for (const page of original.pages) { const entries = []; const pageRoot = path.join(jobDirectory(originalJobId), `pages/page-${String(page.page).padStart(4, '0')}/regions`); for (const region of page.regions) { const dir = path.join(pageRoot, region.regionId); let candidateFile = path.join(dir, 'candidate.json'); if (!fs.existsSync(candidateFile)) candidateFile = path.join(recoveryDir, 'salvaged', `page-${page.page}`, region.regionId, 'candidate.json'); if (!fs.existsSync(candidateFile)) candidateFile = path.join(recoveryDir, 'recovered', `page-${page.page}`, region.regionId, 'candidate.json'); if (fs.existsSync(candidateFile)) entries.push({ ...JSON.parse(fs.readFileSync(path.join(dir, 'region.json'), 'utf8')), candidate: JSON.parse(fs.readFileSync(candidateFile, 'utf8')) }) } const merged = mergeRegionCandidates(entries); const expected = page.regions.length; const value = { sourceId: original.sourceId, sourcePage: page.page, regions: entries.map((e) => ({ regionId: e.regionId, column: e.column, nativeBox: e.nativeBox, cropUrl: e.cropUrl, cropSha256: e.crop?.sha256 || null, lines: e.candidate.lines })), lines: merged.lines, disagreements: merged.disagreements, failedRegions: page.failures, recoveryId, originalJobId, coverage: expected ? entries.length / expected : 0, machineDraftWarning: 'UNVERIFIED MACHINE TRANSCRIPTION — NOT A SCHOLARLY EDITION', ...batchPolicy }; const out = path.join(recoveryDir, 'pages', `page-${String(page.page).padStart(4, '0')}`, 'page-candidate.json'); fs.mkdirSync(path.dirname(out), { recursive: true }); json(out, value); pageCandidates.set(page.page, { entries, merged, expected, candidate: value }) }
  const usableNew = salvaged.length + recovered.length; const recoverySuccessRate = failures.length ? usableNew / failures.length : 1; json(path.join(recoveryDir, 'recovery-summary.json'), { schemaVersion: '1.0', originalJobId, recoveryId, failureCount: failures.length, skippedPreviouslyUsable, categories, salvagedCount: salvaged.length, recoveredCount: recovered.length, stillFailedCount: stillFailed.length, recoverySuccessRate, salvaged, recovered, stillFailed, primary, fallbackModels: fallbacks, canonical: false, candidateOnly: true }); json(path.join(recoveryDir, 'failure-categories.json'), categories); json(path.join(recoveryDir, 'model-routing.json'), { primary, fallbackModels: fallbacks, recovered, canonical: false }); const exportDir = path.join(root, 'exports', 'batch-recovery', recoveryId); fs.mkdirSync(exportDir, { recursive: true }); fs.cpSync(recoveryDir, exportDir, { recursive: true }); console.log(JSON.stringify({ originalJobId, recoveryId, recoverySuccessRate, categories, skippedPreviouslyUsable, salvaged: salvaged.length, recovered: recovered.length, stillFailed: stillFailed.length, usableRegions: [...pageCandidates.values()].reduce((n, p) => n + p.entries.length, 0), lines: [...pageCandidates.values()].reduce((n, p) => n + p.merged.lines.length, 0), exportPath: exportDir, pages20to29Started: false, resumeCommand: `GIGAS_VISION_PROVIDER=gemini GIGAS_VISION_MODEL=gemini-3-flash-preview GIGAS_VISION_FALLBACK_MODELS=gemini-3-flash-preview GIGAS_VISION_MAX_OUTPUT_TOKENS=8192 GIGAS_GEMINI_THINKING_LEVEL=minimal GIGAS_RECOVERY_TIMEOUT_MS=180000 npm run transcribe:recovery -- --job=${originalJobId}` }, null, 2))
}
main().catch((error) => { console.error(JSON.stringify({ error: error.message }, null, 2)); process.exitCode = 1 })
