import fs from 'node:fs'
import path from 'node:path'
import { root, sha256, parseArgs } from '../src/manuscript/source-ingestion.js'
import { atomicJson } from '../src/manuscript/batch-pipeline.js'
import { readTextProviderConfig, invokeTextModel } from '../src/manuscript/text-provider.js'
import { loadTranslationSource, chunks, translationPrompt, normalizeTranslationChunk, coverage, translationPolicy } from '../src/manuscript/translation-pipeline.js'

const args = parseArgs(process.argv.slice(2)); const sourceJobId = args['source-job'] || 'batch-2026-07-14T01-26-26-060Z-21001'; const pages = Array.from({ length: 10 }, (_, i) => i + 20)
if (args.pages && args.pages !== '20-29') throw new Error('translation_pilot_range_must_be_20-29')
const config = readTextProviderConfig(); const runId = args.run || `translation-${new Date().toISOString().replace(/[:.]/g, '-')}-${process.pid}`
const runDir = path.join(root, 'data/candidates/translations', runId); const exportDir = path.join(root, 'exports/translation-pilots', runId); const publicDir = path.join(root, 'public/translation-pilot')
fs.mkdirSync(runDir, { recursive: true }); fs.mkdirSync(exportDir, { recursive: true }); fs.mkdirSync(publicDir, { recursive: true })
const jobFile = path.join(runDir, 'job.json'); const sourcePages = loadTranslationSource(sourceJobId, pages)
let job = fs.existsSync(jobFile) ? JSON.parse(fs.readFileSync(jobFile, 'utf8')) : { schemaVersion: '1.0', runId, sourceJobId, pagesRequested: pages, provider: config.provider, model: config.model, state: 'prepared', createdAt: new Date().toISOString(), requestCount: 0, pages: sourcePages.map((page) => ({ page: page.page, state: 'queued', sourceLines: page.lines.length, chunks: [], coverage: null })), ...translationPolicy }
if (job.provider !== config.provider || job.model !== config.model) { job.providerChanges ||= []; job.providerChanges.push({ previousProvider: job.provider, previousModel: job.model, provider: config.provider, model: config.model, reason: 'configured_model_unavailable', changedAt: new Date().toISOString() }); job.provider = config.provider; job.model = config.model }
atomicJson(jobFile, job)
if (!config.apiKey) { job.state = 'blocked'; job.failureClassification = 'credential_missing'; job.requiredEnvironmentVariable = config.apiKeyEnv; atomicJson(jobFile, job); console.log(JSON.stringify(job, null, 2)); process.exit(1) }
job.state = 'running'; atomicJson(jobFile, job)

for (const sourcePage of sourcePages) {
  const pageState = job.pages.find((page) => page.page === sourcePage.page); const pageDir = path.join(runDir, `pages/page-${String(sourcePage.page).padStart(4, '0')}`); fs.mkdirSync(pageDir, { recursive: true }); pageState.state = 'translating'; atomicJson(jobFile, job)
  const pageChunks = chunks(sourcePage.lines, Number(args['chunk-size'] || 50)); const translated = []
  for (let index = 0; index < pageChunks.length; index++) {
    const chunk = pageChunks[index]; const chunkId = `chunk-${String(index + 1).padStart(3, '0')}`; const dir = path.join(pageDir, chunkId); const resultFile = path.join(dir, 'result.json'); fs.mkdirSync(dir, { recursive: true }); let prior = null; let requestLines = chunk
    if (fs.existsSync(resultFile)) { prior = JSON.parse(fs.readFileSync(resultFile, 'utf8')); if (prior.status === 'completed') { translated.push(...prior.records.map((record) => ({ ...record, translationProvider: record.translationProvider || prior.provider, translationModel: record.translationModel || prior.model }))); continue } if (prior.status === 'partial' && !args['retry-partial']) { translated.push(...prior.records); continue } if (prior.status === 'partial') { const missing = new Set(prior.records.filter((record) => !record.literalEnglish || !record.readableEnglish).map((record) => record.sourceLineId)); requestLines = chunk.filter((line) => missing.has(line.sourceLineId)); if (!requestLines.length) { translated.push(...prior.records); continue } } }
    if (fs.existsSync(resultFile)) { const attempts = path.join(dir, 'attempts'); fs.mkdirSync(attempts, { recursive: true }); const attemptDir = path.join(attempts, `attempt-${String(fs.readdirSync(attempts).length + 1).padStart(2, '0')}`); fs.mkdirSync(attemptDir); for (const name of ['request-manifest.json', 'raw-response.txt', 'raw-response-retry.txt', 'provider-response.json', 'provider-response-retry.json', 'result.json']) if (fs.existsSync(path.join(dir, name))) fs.copyFileSync(path.join(dir, name), path.join(attemptDir, name)) }
    const prompt = translationPrompt(requestLines); const requestManifest = { schemaVersion: '1.0', requestId: `${runId}-${sourcePage.page}-${chunkId}-${Date.now()}`, provider: config.provider, model: config.model, recovery: Boolean(prior), sourcePage: sourcePage.page, sourceLineIds: requestLines.map((line) => line.sourceLineId), sourceHash: sha256(Buffer.from(JSON.stringify(requestLines))), promptSha256: sha256(Buffer.from(prompt)), createdAt: new Date().toISOString(), credentialsPersisted: false, canonical: false }
    atomicJson(path.join(dir, 'request-manifest.json'), requestManifest); job.requestCount++; pageState.chunks[index] = { chunkId, state: 'request_started', lines: chunk.length, requestedMissingLines: requestLines.length }; atomicJson(jobFile, job)
    let response = await invokeTextModel({ prompt, requestId: requestManifest.requestId, config })
    if (response.rawProviderResponse !== undefined) fs.writeFileSync(path.join(dir, 'raw-response.txt'), response.rawProviderResponse)
    atomicJson(path.join(dir, 'provider-response.json'), { ...response, rawProviderResponse: undefined, providerEnvelope: undefined, assistantContent: undefined })
    if (response.failureClassification === 'rate_limited') { const retryAfter = Number(response.responseHeaders?.['retry-after'] || 5); await new Promise((resolve) => setTimeout(resolve, Math.min(60000, Math.max(1000, retryAfter * 1000)))); response = await invokeTextModel({ prompt, requestId: `${requestManifest.requestId}-retry`, config }); job.requestCount++; if (response.rawProviderResponse !== undefined) fs.writeFileSync(path.join(dir, 'raw-response-retry.txt'), response.rawProviderResponse); atomicJson(path.join(dir, 'provider-response-retry.json'), { ...response, rawProviderResponse: undefined, providerEnvelope: undefined, assistantContent: undefined }) }
    const normalized = normalizeTranslationChunk(response.parsedOutput, requestLines); const recovered = new Map(normalized.records.filter((record) => record.literalEnglish && record.readableEnglish).map((record) => [record.sourceLineId, { ...record, translationProvider: response.provider, translationModel: response.actualModel }]))
    const records = prior ? prior.records.map((record) => recovered.get(record.sourceLineId) || { ...record, translationProvider: record.translationProvider || prior.provider, translationModel: record.translationModel || prior.model }) : normalized.records.map((record) => ({ ...record, translationProvider: response.provider, translationModel: response.actualModel }))
    const result = { schemaVersion: '1.0', status: response.status === 'completed' && normalized.valid ? (records.some((record) => !record.literalEnglish || !record.readableEnglish) ? 'partial' : 'completed') : prior?.status === 'partial' ? 'partial' : 'blocked', provider: response.provider, model: response.actualModel, providerResponseId: response.providerResponseId || null, rawResponsePath: response.rawProviderResponse !== undefined ? 'raw-response.txt' : null, rawResponseSha256: response.rawProviderResponseHash || '', parsedOutputSha256: response.parsedOutputHash || '', usage: response.usage || null, durationMs: response.durationMs, failureClassification: response.failureClassification, records, validationFindings: [...(prior?.validationFindings || []), ...normalized.findings], recoveredLines: recovered.size, ...translationPolicy }
    atomicJson(resultFile, result); translated.push(...result.records); pageState.chunks[index] = { chunkId, state: result.status, lines: chunk.length, translated: result.records.filter((record) => record.literalEnglish && record.readableEnglish).length }; atomicJson(jobFile, job)
    await new Promise((resolve) => setTimeout(resolve, Number(args['delay-ms'] || 1000)))
  }
  const pageCoverage = coverage(translated); const pageCandidate = { schemaVersion: '1.0', runId, sourceJobId, source: sourcePage, lines: translated, coverage: pageCoverage, machineWarning: 'UNVERIFIED MACHINE TRANSCRIPTION AND TRANSLATION', ...translationPolicy }
  atomicJson(path.join(pageDir, 'page-translation.json'), pageCandidate); pageState.coverage = pageCoverage; pageState.state = pageCoverage.translationCoveragePercentage === 100 ? 'completed' : 'partial'; atomicJson(jobFile, job)
}

const allLines = []; const viewerPages = []
for (const sourcePage of sourcePages) { const file = path.join(runDir, `pages/page-${String(sourcePage.page).padStart(4, '0')}/page-translation.json`); const page = JSON.parse(fs.readFileSync(file)); allLines.push(...page.lines); viewerPages.push({ page: sourcePage.page, folioLabel: sourcePage.folioLabel, imageUrl: sourcePage.image?.sourceUrl || '', sourceWarnings: sourcePage.sourceWarnings, lines: page.lines }) }
job.coverage = coverage(allLines); job.state = job.pages.every((page) => page.state === 'completed') ? 'completed' : 'partial'; job.finishedAt = new Date().toISOString(); atomicJson(jobFile, job)
const manifest = { schemaVersion: '1.0', runId, generatedAt: new Date().toISOString(), provider: config.provider, model: config.model, sourceJobId, pages, coverage: job.coverage, candidatePath: path.relative(root, runDir), canonical: false, candidateOnly: true, reviewRequired: true, machineWarning: 'UNVERIFIED MACHINE TRANSCRIPTION AND TRANSLATION' }
atomicJson(path.join(exportDir, 'manifest.json'), manifest); fs.cpSync(runDir, path.join(exportDir, 'candidate'), { recursive: true }); atomicJson(path.join(publicDir, `${runId}.json`), { ...manifest, pages: viewerPages }); atomicJson(path.join(publicDir, 'latest.json'), { runId, path: `/translation-pilot/${runId}.json`, generatedAt: manifest.generatedAt, canonical: false })
console.log(JSON.stringify({ ...manifest, state: job.state, requestCount: job.requestCount, output: path.relative(root, runDir), export: path.relative(root, exportDir), viewer: `/editor/translation-pilot?run=${runId}` }, null, 2))
