import fs from 'node:fs'
import path from 'node:path'
const root = path.resolve(import.meta.dirname, '..'); const read = (file) => JSON.parse(fs.readFileSync(path.join(root, file), 'utf8')); const readDir = (dir) => fs.existsSync(path.join(root, dir)) ? fs.readdirSync(path.join(root, dir)).filter((file) => file.endsWith('.json')).map((file) => read(`${dir}/${file}`)) : []
const errors = []; const warnings = []; const states = new Set(['placeholder','draft','machine-assisted','internally-reviewed','externally-reviewed','verified','disputed','deprecated','reviewed','unreviewed']); const contentTypes = new Set(['manuscript image','thumbnail','tile manifest','transcription','translation','catalog metadata','historical note','linguistic note','bibliography','rights statement']); const authorities = read('src/data/authorities.json'); const citations = read('src/data/citations.json'); const licenses = read('src/data/licenses.json'); const contributors = read('src/data/contributors.json'); const qualifications = read('src/data/reviewer-qualifications.json'); const authorityMatrix = read('src/data/review-authority-matrix.json'); const index = read('src/data/codex-index.json'); const metadata = read('src/data/manuscript-metadata.json'); const captures = readDir('src/data/source-captures'); const transformations = read('src/data/asset-transformations.json'); const methods = read('src/data/translation-methods.json'); const sourceStrategies = readDir('src/data/source-strategies'); const sourceIds = new Set(captures.map((item) => item.id)); const authorityIds = new Set(authorities.map((item) => item.id)); const citationIds = new Set(citations.map((item) => item.id)); const licenseIds = new Set(licenses.map((item) => item.id)); const contributorIds = new Set(contributors.map((item) => item.id)); const methodIds = new Set(methods.map((item) => item.id)); const unique = (items, label) => { const seen = new Set(); for (const item of items) { if (!item.id) errors.push(`${label}: missing id`); else if (seen.has(item.id)) errors.push(`${label}: duplicate id ${item.id}`); seen.add(item.id) } }
unique(authorities, 'authority'); unique(citations, 'citation'); unique(licenses, 'license'); unique(contributors, 'contributor'); unique(captures, 'source capture'); unique(transformations, 'transformation'); unique(index.folios, 'index folio')
for (const item of [...authorities, ...citations, ...licenses, ...contributors]) if (!states.has(item.verificationState)) errors.push(`${item.id}: invalid verification state ${item.verificationState}`)
for (const qualification of qualifications) { if (!contributorIds.has(qualification.contributorId)) errors.push(`${qualification.id}: unknown contributor`); if (!['unverified','project-designated','externally-documented','verified','disputed','expired'].includes(qualification.state)) errors.push(`${qualification.id}: invalid qualification state`) }
for (const policy of authorityMatrix) if (!policy.scope || !policy.minimumQualificationState) errors.push(`review authority matrix: incomplete policy ${policy.scope}`)
for (const capture of captures) { if (!contentTypes.has(capture.contentType)) errors.push(`${capture.id}: unsupported contentType ${capture.contentType}`); if (!contributorIds.has(capture.capturedBy)) errors.push(`${capture.id}: unknown contributor ${capture.capturedBy}`); if (!citationIds.has(capture.citationId)) errors.push(`${capture.id}: unknown citation ${capture.citationId}`); for (const id of capture.authorityIds || []) if (!authorityIds.has(id)) errors.push(`${capture.id}: unknown authority ${id}`); if (!states.has(capture.verificationState)) errors.push(`${capture.id}: invalid verification state`); if (capture.contentType === 'manuscript image' && !capture.rightsReviewed) warnings.push(`${capture.id}: rights not reviewed`) }
for (const citation of citations) { if (citation.licenseId && !licenseIds.has(citation.licenseId)) errors.push(`${citation.id}: unknown license ${citation.licenseId}`); for (const id of citation.authorityIds || []) if (!authorityIds.has(id)) errors.push(`${citation.id}: unknown authority ${id}`) }
for (const license of licenses) if (license.allowsRedistribution && license.verificationState === 'placeholder') errors.push(`${license.id}: placeholder license cannot grant redistribution`)
if (!metadata.title || !metadata.language || !metadata.verificationHistory) errors.push('manuscript metadata: missing required metadata')
const ids = new Set(); for (const entry of index.folios) { ids.add(entry.id); if (!states.has(entry.verificationStatus)) errors.push(`${entry.id}: invalid index verificationStatus ${entry.verificationStatus}`); const file = `src/data/folios/${entry.id}.json`; if (!fs.existsSync(path.join(root, file))) errors.push(`${file}: missing folio record`); else { const folio = read(file); for (const key of ['languageNotes','historicalNotes','villanuevaCommentary','uncertainReadings']) if (!Array.isArray(folio[key])) errors.push(`${file}: ${key} must be an array`); for (const [layer, source] of Object.entries(folio.sources || {})) { if (!states.has(source.verificationState)) errors.push(`${folio.id}.sources.${layer}: invalid verification state`); for (const id of source.citationIds || []) if (!citationIds.has(id)) errors.push(`${folio.id}.sources.${layer}: unknown citation ${id}`); for (const id of source.authorityIds || []) if (!authorityIds.has(id)) errors.push(`${folio.id}.sources.${layer}: unknown authority ${id}`); if (source.licenseId && !licenseIds.has(source.licenseId)) errors.push(`${folio.id}.sources.${layer}: unknown license ${source.licenseId}`) } for (const reading of folio.uncertainReadings || []) { if (reading.confidence !== undefined && (reading.confidence < 0 || reading.confidence > 1)) errors.push(`${folio.id}.${reading.id || 'uncertain-reading'}: confidence must be between 0 and 1`); if (reading.alternatives && !Array.isArray(reading.alternatives)) errors.push(`${folio.id}.${reading.id || 'uncertain-reading'}: alternatives must be an array`) } for (const region of folio.regions || []) { if ([region.x, region.y, region.width, region.height].some((value) => !Number.isFinite(value) || value < 0 || value > 1)) errors.push(`${folio.id}.${region.id || 'region'}: coordinates must be between 0 and 1`); if (region.width <= 0 || region.height <= 0) errors.push(`${folio.id}.${region.id || 'region'}: dimensions must be positive`) } if (entry.verificationStatus !== 'placeholder' && !folio.sources?.image?.citationIds?.length) warnings.push(`${folio.id}: non-placeholder index status without image citation`) } }
for (const transformation of transformations) { if (!transformation.sourceAsset || !transformation.outputAsset) errors.push(`${transformation.id}: missing sourceAsset or outputAsset`) }
for (const method of methods) if (!states.has(method.verificationState)) errors.push(`${method.id}: invalid translation method state`)
for (const strategy of sourceStrategies) { if (!strategy.folioId || !strategy.selectedMethod) errors.push(`${strategy.id}: missing folioId or selectedMethod`); if (!['human-project-draft','institutional-transcription','published-edition'].includes(strategy.selectedMethod)) errors.push(`${strategy.id}: unsupported textual source method ${strategy.selectedMethod}`); for (const id of strategy.sourcesExamined || []) if (!citationIds.has(id)) errors.push(`${strategy.id}: unknown citation ${id}`) }
const regions = readDir('src/data/regions'); const alignments = readDir('src/data/alignments').flatMap((item) => Array.isArray(item) ? item : []); const reviewAssignments = fs.existsSync(path.join(root, 'src/data/reviews/assignments-002r.json')) ? read('src/data/reviews/assignments-002r.json') : []; const reviewFindings = fs.existsSync(path.join(root, 'src/data/reviews/findings-002r.json')) ? read('src/data/reviews/findings-002r.json') : []; const changes = readDir('src/data/change-history').flatMap((item) => Array.isArray(item) ? item : []); for (const region of regions) for (const item of region) { if (!/^region-002r-/.test(item.id)) errors.push(`${item.id}: invalid stable region ID`); if ([item.x,item.y,item.width,item.height].some((value) => !Number.isFinite(value) || value < 0 || value > 1)) errors.push(`${item.id}: coordinates must remain between 0 and 1`) }
for (const assignment of reviewAssignments) { if (!states.has(assignment.verificationState)) errors.push(`${assignment.id}: invalid review verification state`); if (!['open','in review','changes requested','accepted','blocked','deferred'].includes(assignment.status)) errors.push(`${assignment.id}: invalid review status`) }
for (const finding of reviewFindings) if (!['informational','minor','major','blocking'].includes(finding.severity)) errors.push(`${finding.id}: invalid finding severity`)
for (const change of changes) { if (!change.contributorId || !contributorIds.has(change.contributorId)) errors.push(`${change.id}: unknown contributor`); for (const id of change.citationIds || []) if (!citationIds.has(id)) errors.push(`${change.id}: unknown citation ${id}`) }
if (!fs.existsSync(path.join(root, 'public/tiles/real/002r/manifest.json'))) errors.push('pilot tile manifest missing')
for (const warning of warnings) console.warn(`WARNING: ${warning}`); for (const error of errors) console.error(`ERROR: ${error}`); console.log(`Validated ${ids.size} folios, ${captures.length} source captures, ${authorities.length} authorities, ${citations.length} citations, ${licenses.length} licenses, ${transformations.length} transformations.`); if (errors.length) process.exit(1)
