import fs from 'node:fs'
import path from 'node:path'
import { spawn } from 'node:child_process'
import { candidateRoot, imageDimensions, mediaType, sha256 } from './source-ingestion.js'

function findExecutable(value) { if (!value) return null; if (path.isAbsolute(value) && fs.existsSync(value)) return value; if (!path.isAbsolute(value)) { const result = spawn('which', [value]); return result } return null }
async function resolveExecutable(value) { if (value && path.isAbsolute(value) && fs.existsSync(value)) return value; const name = value || 'opj_decompress'; return new Promise((resolve) => { const child = spawn('which', [name]); let out = ''; child.stdout.on('data', (chunk) => { out += chunk }); child.on('close', (code) => resolve(code === 0 && out.trim() ? out.trim() : null)); child.on('error', () => resolve(null)) }) }
function writeDiagnostics(directory, diagnostics) { const file = path.join(directory, 'decoder.json'); fs.mkdirSync(directory, { recursive: true }); fs.writeFileSync(file, JSON.stringify(diagnostics, null, 2) + '\n'); return file }
export async function decodeJp2ToPng(inputPath) { const input = path.resolve(inputPath); const directory = fs.mkdtempSync(path.join(candidateRoot, 'transmitted-jp2-')); const output = path.join(directory, 'transmitted.png'); const configured = process.env.GIGAS_JP2_DECODER || 'opj_decompress'; const executable = await resolveExecutable(configured); const customScript = process.env.GIGAS_JP2_DECODER_SCRIPT; const command = customScript ? [executable || configured, customScript, '--input', input, '--output', output] : [executable || configured, '-i', input, '-o', output]; const started = Date.now(); const diagnostics = { success: false, executable: executable || configured, command, exitCode: null, stdout: '', stderr: '', elapsedMs: 0, outputPath: output, outputExists: false, outputBytes: 0, mime: null, sha256: null, width: null, height: null }; if (!executable && !customScript) { diagnostics.stderr = `decoder executable not found: ${configured}`; diagnostics.elapsedMs = Date.now() - started; diagnostics.decoderPath = writeDiagnostics(directory, diagnostics); const error = new Error('jp2_decoder_not_found'); error.diagnostics = diagnostics; throw error } await new Promise((resolve) => { const child = spawn(command[0], command.slice(1), { stdio: ['ignore', 'pipe', 'pipe'] }); child.stdout.on('data', (chunk) => { diagnostics.stdout += chunk.toString() }); child.stderr.on('data', (chunk) => { diagnostics.stderr += chunk.toString() }); child.on('error', (error) => { diagnostics.stderr += error.message }); child.on('close', (code) => { diagnostics.exitCode = code; resolve() }) }); diagnostics.elapsedMs = Date.now() - started; diagnostics.outputExists = fs.existsSync(output); if (diagnostics.outputExists) { diagnostics.outputBytes = fs.statSync(output).size; const bytes = fs.readFileSync(output); diagnostics.mime = mediaType(output); diagnostics.sha256 = sha256(bytes); const dimensions = imageDimensions(bytes, 'image/png'); diagnostics.width = dimensions?.width || null; diagnostics.height = dimensions?.height || null; diagnostics.pngSignature = bytes.subarray(0, 4).equals(Buffer.from([137, 80, 78, 71])) } diagnostics.success = diagnostics.exitCode === 0 && diagnostics.outputExists && diagnostics.outputBytes > 0 && diagnostics.pngSignature === true; diagnostics.decoderPath = writeDiagnostics(directory, diagnostics); if (!diagnostics.success) { const error = new Error('jp2_decode_failure'); error.diagnostics = diagnostics; throw error } const buffer = fs.readFileSync(output); return { buffer, outputPath: output, diagnostics, dimensions: { width: diagnostics.width, height: diagnostics.height }, mime: 'image/png', sha256: diagnostics.sha256 } }
